export interface ExerciseItem {
  id: string;
  name: string;
  category: 
    | 'strength' 
    | 'calisthenics' 
    | 'powerlifting' 
    | 'olympic' 
    | 'hiit' 
    | 'functional' 
    | 'yoga_mobility' 
    | 'combat' 
    | 'home';
  muscle_group: 
    | 'chest' 
    | 'back' 
    | 'shoulders' 
    | 'biceps' 
    | 'triceps' 
    | 'forearms' 
    | 'quads' 
    | 'hamstrings' 
    | 'glutes' 
    | 'calves' 
    | 'core' 
    | 'full_body';
  secondary_muscles?: string[];
  equipment: 
    | 'barbell' 
    | 'dumbbell' 
    | 'cable' 
    | 'machine' 
    | 'kettlebell' 
    | 'bodyweight' 
    | 'bands' 
    | 'cardio_machine' 
    | 'other';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  instructions: string[];
  tips?: string[];
  image_url?: string;
  video_url?: string;
}

export const getExerciseVideoUrl = (exercise: ExerciseItem): string => {
  if (exercise.video_url) return exercise.video_url;
  const q = encodeURIComponent(`how to do ${exercise.name} exercise form tutorial`);
  return `https://www.youtube.com/results?search_query=${q}`;
};

export interface WorkoutTemplate {
  id: string;
  title: string;
  category: string;
  duration_min: number;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  description: string;
  icon: string;
  exercises: {
    exercise_id: string;
    exercise_name: string;
    target_sets: number;
    target_reps?: string;
    target_duration_sec?: number;
    muscle_group: string;
  }[];
}

export const EXERCISE_CATEGORIES = [
  { id: 'all', name: 'All Disciplines', icon: 'layers', color: '#c3f400' },
  { id: 'strength', name: 'Strength & Hypertrophy', icon: 'activity', color: '#38bdf8' },
  { id: 'powerlifting', name: 'Powerlifting (Big 3)', icon: 'shield', color: '#f97316' },
  { id: 'calisthenics', name: 'Calisthenics & Bodyweight', icon: 'zap', color: '#a855f7' },
  { id: 'olympic', name: 'Olympic Weightlifting', icon: 'award', color: '#eab308' },
  { id: 'hiit', name: 'HIIT & Cardio', icon: 'trending-up', color: '#ef4444' },
  { id: 'functional', name: 'CrossFit & Functional', icon: 'cpu', color: '#10b981' },
  { id: 'yoga_mobility', name: 'Yoga & Mobility', icon: 'sun', color: '#06b6d4' },
  { id: 'combat', name: 'Combat & Boxing', icon: 'target', color: '#ec4899' },
  { id: 'home', name: 'Home & Minimal Gear', icon: 'home', color: '#84cc16' },
];

export const MUSCLE_GROUPS = [
  { id: 'all', name: 'All Muscles' },
  { id: 'chest', name: 'Chest' },
  { id: 'back', name: 'Back' },
  { id: 'shoulders', name: 'Shoulders' },
  { id: 'biceps', name: 'Biceps' },
  { id: 'triceps', name: 'Triceps' },
  { id: 'forearms', name: 'Forearms' },
  { id: 'quads', name: 'Quads' },
  { id: 'hamstrings', name: 'Hamstrings' },
  { id: 'glutes', name: 'Glutes' },
  { id: 'calves', name: 'Calves' },
  { id: 'core', name: 'Core & Abs' },
  { id: 'full_body', name: 'Full Body' },
];

export const EQUIPMENT_TYPES = [
  { id: 'all', name: 'All Equipment' },
  { id: 'barbell', name: 'Barbell' },
  { id: 'dumbbell', name: 'Dumbbell' },
  { id: 'cable', name: 'Cable' },
  { id: 'machine', name: 'Machine' },
  { id: 'kettlebell', name: 'Kettlebell' },
  { id: 'bodyweight', name: 'Bodyweight' },
  { id: 'bands', name: 'Bands' },
  { id: 'cardio_machine', name: 'Cardio' },
  { id: 'other', name: 'Specialty / Other' },
];

// Universal Exhaustive Exercise Database With Visual Images & Detailed Biomechanics
export const UNIVERSAL_EXERCISES: ExerciseItem[] = [
  // ==========================================
  // 1. CHEST (Strength & Hypertrophy)
  // ==========================================
  {
    id: 'ch-01',
    name: 'Barbell Flat Bench Press',
    category: 'strength',
    muscle_group: 'chest',
    secondary_muscles: ['triceps', 'front delts'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Lie flat on the bench with eyes directly under the bar and feet firmly planted on the floor.',
      'Grip the bar slightly wider than shoulder-width with wrists stacked straight over forearms.',
      'Unrack the bar, pull your scapula down and back, and lower under control to mid-sternum.',
      'Drive feet through the floor and press the bar explosively back to lockout position.',
    ],
    tips: [
      'Pinch shoulder blades together throughout the lift to protect rotator cuffs.',
      'Do not bounce the bar off your ribcage.',
      'Keep elbows tucked at a 45-degree angle rather than flared 90 degrees.',
    ],
  },
  {
    id: 'ch-02',
    name: 'Incline Dumbbell Press',
    category: 'strength',
    muscle_group: 'chest',
    secondary_muscles: ['front delts', 'triceps'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Set bench angle to 30° - 45° incline.',
      'Kick dumbbells up to your shoulders with your knees as you lean back.',
      'Lower the dumbbells steadily until you feel a deep stretch across your clavicular upper chest.',
      'Press upward in a slight converging arc, squeezing your upper pectorals at the peak.',
    ],
    tips: [
      'Do not set the incline too steep (over 45°) or the shoulders will take over.',
      'Keep wrists straight and avoid banging dumbbells together at top.',
    ],
  },
  {
    id: 'ch-03',
    name: 'Decline Barbell Bench Press',
    category: 'strength',
    muscle_group: 'chest',
    secondary_muscles: ['triceps', 'lower chest'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Secure your legs in the decline bench pads and lie back comfortably.',
      'Unrack the bar with a medium-wide grip over your lower sternum.',
      'Lower smoothly to your lower pectoral line and press upward in a vertical path.',
    ],
    tips: [
      'Provides high recruitment for lower pectoralis major with reduced shoulder joint stress.',
    ],
  },
  {
    id: 'ch-04',
    name: 'Standing Cable Chest Flyes',
    category: 'strength',
    muscle_group: 'chest',
    secondary_muscles: ['front delts', 'serratus anterior'],
    equipment: 'cable',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Set pulleys at chest height. Take handles and step forward in a staggered split stance.',
      'Keep a slight bend in your elbows and open arms out wide for a deep pectoral stretch.',
      'Bring hands together in front of your chest in a hugging motion, squeezing hard for 1 full second.',
      'Resist the weight smoothly on the return arc.',
    ],
    tips: [
      'Maintain constant cable tension at every millimeter of the movement.',
    ],
  },
  {
    id: 'ch-05',
    name: 'Low-to-High Incline Cable Flyes',
    category: 'strength',
    muscle_group: 'chest',
    secondary_muscles: ['upper chest', 'front delts'],
    equipment: 'cable',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Set pulleys at lowest position with single D-handles.',
      'Stand upright, stagger feet, and scoop your arms upward and inward to eye level.',
      'Hold the peak contraction of your upper chest for 1 second, then lower slowly.',
    ],
    tips: [
      'Directly activates the clavicular head of the pectoralis.',
    ],
  },
  {
    id: 'ch-06',
    name: 'Pec Deck / Seated Chest Fly Machine',
    category: 'strength',
    muscle_group: 'chest',
    secondary_muscles: ['front delts'],
    equipment: 'machine',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Adjust seat height so handles align directly with your mid-chest line.',
      'Press handles together until they touch, squeezing your chest fibers completely.',
      'Slowly open arms wide without allowing the weight stack to slam.',
    ],
    tips: ['Keep your spine pressed against the back pad throughout.'],
  },
  {
    id: 'ch-07',
    name: 'Dumbbell Pullover',
    category: 'strength',
    muscle_group: 'chest',
    secondary_muscles: ['lats', 'serratus anterior', 'triceps'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Lie perpendicular across a flat bench with your upper back supported and hips dropped.',
      'Hold a single dumbbell with both hands forming a diamond cup under the inner plate.',
      'Lower the dumbbell behind your head in a wide arc until chest and ribcage expand fully.',
      'Pull the dumbbell back over your chest contracting your chest and serratus.',
    ],
    tips: ['Keep a slight bend in your elbows and focus on ribcage expansion.'],
  },
  {
    id: 'ch-08',
    name: 'Weighted Chest Dips',
    category: 'strength',
    muscle_group: 'chest',
    secondary_muscles: ['triceps', 'front delts'],
    equipment: 'bodyweight',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Grip parallel dip bars and support your bodyweight.',
      'Lean your torso forward 30 degrees with elbows flared slightly outward.',
      'Lower your body until your shoulders are just below your elbows.',
      'Drive powerfully through your palms back to lockout.',
    ],
    tips: ['Leaning forward shifts emphasis to chest; staying vertical targets triceps.'],
  },
  {
    id: 'ch-09',
    name: 'Machine Chest Press',
    category: 'strength',
    muscle_group: 'chest',
    secondary_muscles: ['triceps', 'front delts'],
    equipment: 'machine',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Sit firmly against the back pad with handles aligned at mid-chest.',
      'Press handles forward until arms are almost fully extended.',
      'Return slowly under eccentric control, feeling the stretch across pectorals.',
    ],
    tips: ['Excellent for beginners or drop sets safely without spotters.'],
  },
  {
    id: 'ch-10',
    name: 'Flat Dumbbell Chest Flyes',
    category: 'strength',
    muscle_group: 'chest',
    secondary_muscles: ['front delts'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Lie flat on bench holding dumbbells with palms facing each other above chest.',
      'With elbows slightly bent, lower dumbbells in a wide arc until chest is stretched.',
      'Bring dumbbells back to start position like hugging a barrel.',
    ],
    tips: ['Do not drop dumbbells below bench level to protect shoulder capsules.'],
  },

  // ==========================================
  // 2. POWERLIFTING (Big 3 & Competition Variations)
  // ==========================================
  {
    id: 'pl-01',
    name: 'Competition Barbell Squat (Low Bar)',
    category: 'powerlifting',
    muscle_group: 'quads',
    secondary_muscles: ['glutes', 'hamstrings', 'lower back', 'core'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Position bar across posterior deltoids in low-bar shelf position.',
      'Unrack with 2-3 step walkout, feet slightly wider than shoulders, toes turned 15-30° out.',
      'Take a deep 360° intra-abdominal breath and brace core like preparing for a punch.',
      'Hinge hips and knees simultaneously, squatting until hip crease is below the top of kneecap.',
      'Drive hips up with explosive power through the mid-foot.',
    ],
    tips: [
      'Keep knees tracking in line with toes throughout the descent and ascent.',
      'Maintain rigid thoracic spine and neutral neck alignment.',
    ],
  },
  {
    id: 'pl-02',
    name: 'Pause Squat (2-Second Hold at Bottom)',
    category: 'powerlifting',
    muscle_group: 'quads',
    secondary_muscles: ['glutes', 'core', 'hip adductors'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Descend under control into a full-depth squat.',
      'Come to a complete motionless stop in the hole for a strict 2-second count.',
      'Eliminate stretch reflex and drive upwards out of the bottom with pure concentric force.',
    ],
    tips: ['Builds extreme starting power and absolute confidence in the hole.'],
  },
  {
    id: 'pl-03',
    name: 'Competition Paused Bench Press',
    category: 'powerlifting',
    muscle_group: 'chest',
    secondary_muscles: ['triceps', 'front delts', 'lats'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Establish a tight arch, pinch scapulae into bench, and plant heels firmly.',
      'Unrack bar, stabilize over shoulders, and lower smoothly to lower sternum.',
      'Pause motionless on chest until the imaginary "PRESS" command (1-2 seconds).',
      'Drive heels through floor (leg drive) and press bar in a slight backward J-curve to lockout.',
    ],
    tips: [
      'Buttocks and head must remain in contact with bench throughout.',
      'Tuck elbows 45-70° to recruit lats and triceps.',
    ],
  },
  {
    id: 'pl-04',
    name: 'Spoto Press (Hover 1-Inch Above Chest)',
    category: 'powerlifting',
    muscle_group: 'chest',
    secondary_muscles: ['triceps', 'shoulders', 'lats'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Lower the barbell with maximum control until it hovers exactly 1 inch above chest.',
      'Hold the hovering position motionless for 1-2 seconds under maximum muscular tension.',
      'Press explosively back up without letting the bar touch your jersey.',
    ],
    tips: ['Builds unparalleled mid-range tightness and tricep stability.'],
  },
  {
    id: 'pl-05',
    name: 'Close-Grip Barbell Bench Press',
    category: 'powerlifting',
    muscle_group: 'triceps',
    secondary_muscles: ['chest', 'front delts'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Grip the bar with hands shoulder-width apart (do not grip too narrow to spare wrists).',
      'Lower bar to lower ribcage keeping elbows tucked tightly against your torso.',
      'Drive bar up to lockout, overloading the triceps with heavy compound tonnage.',
    ],
    tips: ['The premier powerlifting movement for bench press lockout strength.'],
  },
  {
    id: 'pl-06',
    name: 'Conventional Barbell Deadlift',
    category: 'powerlifting',
    muscle_group: 'back',
    secondary_muscles: ['glutes', 'hamstrings', 'traps', 'forearms', 'core'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Stand with feet hip-width apart, barbell cutting over mid-foot (1 inch from shins).',
      'Hinge hips back, grip the bar just outside your knees with double-overhand or mixed grip.',
      'Pull chest up, flatten back, pull slack out of the bar until you hear the click.',
      'Push the floor away through your heels, keeping bar dragged against shins and thighs.',
      'Stand tall, locking out hips and knees simultaneously with glutes clenched.',
    ],
    tips: [
      'Never round your lumbar spine under heavy loads.',
      'Engage lats as if squeezing oranges in your armpits to protect your spine.',
    ],
  },
  {
    id: 'pl-07',
    name: 'Sumo Deadlift',
    category: 'powerlifting',
    muscle_group: 'glutes',
    secondary_muscles: ['quads', 'hamstrings', 'adductors', 'back'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Set feet wide near the weight plates with toes pointed outward 45°.',
      'Drop hips down with upright torso, grip bar inside your legs directly under shoulders.',
      'Spread the floor with feet, wedge hips close to bar, and drive floor away.',
      'Lock out hips with strong glute squeeze at top.',
    ],
    tips: ['Shortens the vertical bar travel distance and emphasizes hips/adductors.'],
  },
  {
    id: 'pl-08',
    name: 'Deficit Deadlift (2-Inch Elevated Platform)',
    category: 'powerlifting',
    muscle_group: 'hamstrings',
    secondary_muscles: ['glutes', 'lower back', 'quads'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Stand on a 2-inch rubber plate or low wooden block.',
      'Set up in standard deadlift stance, reaching deeper to grip the bar.',
      'Pull with maximum leg drive from the deep deficit to build immense off-the-floor speed.',
    ],
    tips: ['Develops explosive power for lifters who get stuck at the floor off the pull.'],
  },
  {
    id: 'pl-09',
    name: 'Barbell Block / Rack Pulls (Above Knee)',
    category: 'powerlifting',
    muscle_group: 'back',
    secondary_muscles: ['traps', 'forearms', 'glutes'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Set barbell on blocks or rack pins just below or at knee level.',
      'Grip bar, brace core, and pull to full lockout, overloading upper back and grip.',
    ],
    tips: ['Allows handling supramaximal loads to strengthen the lockout and trap thickness.'],
  },
  {
    id: 'pl-10',
    name: 'Barbell Good Mornings',
    category: 'powerlifting',
    muscle_group: 'hamstrings',
    secondary_muscles: ['glutes', 'lower back', 'erector spinae'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Rack bar on upper back as in a squat with soft knees.',
      'Hinge hips backward until torso is nearly parallel to floor with spine neutral.',
      'Drive hips forward to stand back up contracting glutes and hamstrings.',
    ],
    tips: ['Keep knees slightly bent and do not round lower back.'],
  },

  // ==========================================
  // 3. BACK (Lats, Traps, Rhomboids, Lower Back)
  // ==========================================
  {
    id: 'bk-02',
    name: 'Barbell Bent-Over Row (Pendlay Row)',
    category: 'strength',
    muscle_group: 'back',
    secondary_muscles: ['biceps', 'rear delts', 'core', 'lats'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Hinge at hips until torso is parallel or 45° to floor, knees slightly bent.',
      'Grip barbell overhand, pull bar towards lower abdomen/sternum by driving elbows to ceiling.',
      'Squeeze shoulder blades hard at peak, then lower slowly to full lat stretch.',
    ],
    tips: ['Do not use excessive hip swing to heave the weight up.'],
  },
  {
    id: 'bk-03',
    name: 'Wide-Grip Lat Pulldown',
    category: 'strength',
    muscle_group: 'back',
    secondary_muscles: ['biceps', 'rear delts', 'teres major'],
    equipment: 'cable',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Sit comfortably at lat pulldown station with thighs firmly locked under pads.',
      'Grip long bar wider than shoulder-width with overhand grip.',
      'Lean back slightly (10-15°) and pull bar down to upper clavicle by depressing shoulder blades.',
      'Control the weight back up to a full overhead lat stretch.',
    ],
    tips: ['Pull with your elbows, not your hands, to maximize lat engagement.'],
  },
  {
    id: 'bk-04',
    name: 'Single-Arm Dumbbell Row',
    category: 'strength',
    muscle_group: 'back',
    secondary_muscles: ['biceps', 'lats', 'traps'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Place one knee and same-side hand on a flat bench for torso stability.',
      'Hold dumbbell in opposite hand with spine flat and neutral.',
      'Row the dumbbell up toward your hip crease, pulling through your elbow.',
      'Lower to full stretch at the bottom without twisting spine.',
    ],
    tips: ['Pulling to hip isolates the lower lats; pulling to chest hits upper back.'],
  },
  {
    id: 'bk-05',
    name: 'Seated Cable Row (Close V-Grip)',
    category: 'strength',
    muscle_group: 'back',
    secondary_muscles: ['rhomboids', 'biceps', 'middle traps'],
    equipment: 'cable',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Sit upright on cable bench with feet planted on footrests and knees soft.',
      'Pull V-bar handle towards your lower stomach while driving shoulders back.',
      'Pause for 1 second of peak back contraction, then stretch forward under control.',
    ],
    tips: ['Keep your spine upright and do not excessively rock back and forth.'],
  },
  {
    id: 'bk-06',
    name: 'T-Bar Row (Landmine)',
    category: 'strength',
    muscle_group: 'back',
    secondary_muscles: ['lats', 'traps', 'biceps'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Straddle the T-bar or landmine setup with knees soft and spine flat at 45°.',
      'Grip close-grip handles and pull weight plates toward mid-chest.',
      'Squeeze mid-back at top, then lower with control.',
    ],
    tips: ['Heavy thickness builder for mid-back and rhomboids.'],
  },
  {
    id: 'bk-07',
    name: 'Chest-Supported Incline DB Row',
    category: 'strength',
    muscle_group: 'back',
    secondary_muscles: ['upper back', 'rear delts', 'rhomboids'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Lie face down on an incline bench angled at 30-45 degrees.',
      'Hold dumbbells and row them up, isolating the back completely with zero lower back strain.',
    ],
    tips: ['Completely eliminates lower back fatigue for pure lat/rhomboid isolation.'],
  },
  {
    id: 'bk-08',
    name: 'Face Pulls (Cable Rope)',
    category: 'strength',
    muscle_group: 'back',
    secondary_muscles: ['rear delts', 'rotator cuff', 'upper traps'],
    equipment: 'cable',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Attach rope to high pulley. Grip rope ends with thumbs pointing back.',
      'Step back, pull rope directly towards your eyes/forehead, flaring elbows out and externally rotating shoulders.',
    ],
    tips: ['Crucial exercise for shoulder health, posture, and rear delt hypertrophy.'],
  },
  {
    id: 'bk-09',
    name: 'Straight-Arm Cable Lat Pulldown',
    category: 'strength',
    muscle_group: 'back',
    secondary_muscles: ['lats', 'triceps long head', 'core'],
    equipment: 'cable',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Stand facing high cable bar. Keep arms almost fully straight.',
      'Pull bar down in a sweeping arc to your thighs using pure lat contraction.',
    ],
    tips: ['Isolates lats without fatiguing the biceps.'],
  },
  {
    id: 'bk-10',
    name: 'Barbell Shrugs (Traps)',
    category: 'strength',
    muscle_group: 'back',
    secondary_muscles: ['upper traps', 'forearms'],
    equipment: 'barbell',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Hold barbell in front of thighs with shoulder-width grip.',
      'Elevate shoulders straight up towards your ears without rolling them.',
      'Hold the peak trap contraction for 2 seconds before lowering.',
    ],
    tips: ['Do not roll shoulders; move straight up and down to protect joints.'],
  },

  // ==========================================
  // 4. SHOULDERS (Deltoids & Rotators)
  // ==========================================
  {
    id: 'sh-01',
    name: 'Standing Barbell Overhead Press (OHP)',
    category: 'strength',
    muscle_group: 'shoulders',
    secondary_muscles: ['triceps', 'upper chest', 'core'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Stand tall with bar racked across front shoulders/clavicle.',
      'Squeeze glutes and brace core.',
      'Press bar vertically overhead in a straight line, moving head slightly back then pushing forward under bar.',
      'Lock out elbows overhead with active shoulders.',
    ],
    tips: ['Avoid excessive backward arch in lower spine; squeeze glutes tight.'],
  },
  {
    id: 'sh-02',
    name: 'Seated Dumbbell Shoulder Press',
    category: 'strength',
    muscle_group: 'shoulders',
    secondary_muscles: ['triceps', 'upper traps'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Sit on an upright bench with back support.',
      'Hold dumbbells at shoulder height with palms facing forward.',
      'Press dumbbells overhead until arms are extended, then lower with control to ear level.',
    ],
    tips: ['Lower to ear level for full range of motion.'],
  },
  {
    id: 'sh-03',
    name: 'Arnold Dumbbell Press',
    category: 'strength',
    muscle_group: 'shoulders',
    secondary_muscles: ['front delts', 'lateral delts', 'triceps'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Start with dumbbells held in front of chest, palms facing your face.',
      'As you press upward, rotate wrists so palms face forward at the top.',
      'Reverse rotation smoothly on the way down.',
    ],
    tips: ['Created by Arnold Schwarzenegger to recruit all 3 deltoid heads in one motion.'],
  },
  {
    id: 'sh-04',
    name: 'Standing Dumbbell Lateral Raise',
    category: 'strength',
    muscle_group: 'shoulders',
    secondary_muscles: ['lateral delts', 'traps'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Stand with dumbbells at sides, slight forward torso lean.',
      'Raise dumbbells out to sides until parallel to floor, leading with elbows.',
      'Lower slowly over 2-3 seconds.',
    ],
    tips: ['Do not swing your hips or use body momentum.'],
  },
  {
    id: 'sh-05',
    name: 'Cable Lateral Raise',
    category: 'strength',
    muscle_group: 'shoulders',
    secondary_muscles: ['lateral delts'],
    equipment: 'cable',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Set low cable pulley, grab handle across body with opposite hand.',
      'Raise arm laterally to shoulder height with continuous cable tension.',
    ],
    tips: ['Provides constant resistance even at the bottom stretch position.'],
  },
  {
    id: 'sh-06',
    name: 'Reverse Pec Deck (Rear Delt Fly)',
    category: 'strength',
    muscle_group: 'shoulders',
    secondary_muscles: ['rear delts', 'rhomboids'],
    equipment: 'machine',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Sit facing the pec deck machine pad.',
      'Grip handles and fly arms backwards horizontally, focusing on rear shoulder squeeze.',
    ],
    tips: ['Keeps tension entirely on the rear deltoid and upper rhomboids.'],
  },

  // ==========================================
  // 5. LEGS (Quads, Hamstrings, Glutes, Calves)
  // ==========================================
  {
    id: 'lg-01',
    name: 'Barbell High-Bar Back Squat',
    category: 'strength',
    muscle_group: 'quads',
    secondary_muscles: ['glutes', 'hamstrings', 'core'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Rest barbell securely across upper traps.',
      'Set feet shoulder-width apart with toes turned slightly out.',
      'Inhale, brace abdominal wall, and descend by bending hips and knees until hip crease is below knee level.',
      'Drive powerfully up through the mid-foot back to standing.',
    ],
    tips: ['Keep chest proud and drive knees outward over toes.'],
  },
  {
    id: 'lg-03',
    name: 'Barbell Hip Thrust',
    category: 'strength',
    muscle_group: 'glutes',
    secondary_muscles: ['hamstrings', 'core'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Sit on floor with upper back against flat bench, padded barbell across hip crease.',
      'Plant feet flat, drive hips up until thighs and torso are in straight horizontal alignment.',
      'Squeeze glutes maximally for 2 seconds at the top before lowering.',
    ],
    tips: ['Tuck chin and look forward rather than looking at ceiling to protect lumbar spine.'],
  },
  {
    id: 'lg-04',
    name: 'Romanian Deadlift (RDL)',
    category: 'strength',
    muscle_group: 'hamstrings',
    secondary_muscles: ['glutes', 'lower back'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Stand holding barbell with soft knees.',
      'Push hips directly back while keeping back flat and bar glued to legs.',
      'Descend until you feel a deep hamstring stretch just below the knees, then drive hips forward.',
    ],
    tips: ['Think of pushing your hips back to touch an imaginary wall behind you.'],
  },
  {
    id: 'lg-05',
    name: 'Leg Press (45-Degree)',
    category: 'strength',
    muscle_group: 'quads',
    secondary_muscles: ['glutes', 'hamstrings'],
    equipment: 'machine',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Place feet shoulder-width on the sled platform.',
      'Release safety handles and lower sled until knees reach 90 degrees.',
      'Press back up without locking knees violently.',
    ],
    tips: ['Keep lower back glued to pad; never allow pelvis to round upward.'],
  },
  {
    id: 'lg-06',
    name: 'Bulgarian Split Squat',
    category: 'strength',
    muscle_group: 'quads',
    secondary_muscles: ['glutes', 'hamstrings', 'adductors'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Elevate one rear foot on a bench behind you, front foot 3 feet forward.',
      'Hold dumbbells and drop back knee towards the ground into a deep single-leg lunge.',
      'Drive through front heel to stand up.',
    ],
    tips: ['Exceptional unilateral builder for leg symmetry and athletic knee stability.'],
  },
  {
    id: 'lg-07',
    name: 'Walking Dumbbell Lunges',
    category: 'strength',
    muscle_group: 'quads',
    secondary_muscles: ['glutes', 'calves'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Hold dumbbells at sides and take long strides forward.',
      'Drop back knee almost to the floor on every step, alternating legs continuously.',
    ],
    tips: ['Maintain upright posture without bending forward at the waist.'],
  },
  {
    id: 'lg-08',
    name: 'Lying Hamstring Curl',
    category: 'strength',
    muscle_group: 'hamstrings',
    equipment: 'machine',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Lie face down with roller pad resting against lower calves.',
      'Curl heels up toward glutes against resistance, squeeze at peak, and release slowly.',
    ],
    tips: ['Keep hips pinned to pad so lower back does not hyperextend.'],
  },
  {
    id: 'lg-09',
    name: 'Leg Extensions (Quads Burnout)',
    category: 'strength',
    muscle_group: 'quads',
    equipment: 'machine',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Sit in machine with pad resting on lower shins.',
      'Extend legs to horizontal, contracting quadriceps hard at the peak for 1 second.',
    ],
    tips: ['Control the descent slowly to maximize metabolic quad pump.'],
  },
  {
    id: 'lg-10',
    name: 'Standing Calf Raises',
    category: 'strength',
    muscle_group: 'calves',
    equipment: 'machine',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Place balls of feet on platform ledge, shoulders under pads.',
      'Lower heels for a deep calf stretch, then rise onto tiptoes for peak contraction.',
    ],
    tips: ['Pause for 2 seconds at the bottom stretch to eliminate Achilles tendon bounce.'],
  },

  // ==========================================
  // 6. ARMS & FOREARMS (Biceps, Triceps, Forearms)
  // ==========================================
  {
    id: 'ar-01',
    name: 'Standing Barbell Bicep Curl',
    category: 'strength',
    muscle_group: 'biceps',
    secondary_muscles: ['forearms'],
    equipment: 'barbell',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Hold barbell with underhand grip, elbows pinned to ribcage.',
      'Curl the weight up towards chest by flexing biceps.',
      'Lower bar with full control without swinging torso.',
    ],
    tips: ['Keep upper arms vertical and fixed in space.'],
  },
  {
    id: 'ar-02',
    name: 'Incline Dumbbell Bicep Curl',
    category: 'strength',
    muscle_group: 'biceps',
    secondary_muscles: ['biceps long head'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Sit on an incline bench at 45-60 degrees with arms hanging down.',
      'Curl dumbbells up while keeping elbows pointing down for maximum long-head stretch.',
    ],
    tips: ['Places massive passive stretch on the long head for peak bicep height.'],
  },
  {
    id: 'ar-03',
    name: 'Dumbbell Hammer Curls',
    category: 'strength',
    muscle_group: 'biceps',
    secondary_muscles: ['forearms', 'brachialis'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Hold dumbbells with neutral grip (palms facing each other).',
      'Curl up toward shoulders, targeting forearm and outer arm thickness.',
    ],
    tips: ['Targets the brachialis muscle to push the bicep higher and add arm width.'],
  },
  {
    id: 'ar-04',
    name: 'Preacher Curl (EZ-Bar)',
    category: 'strength',
    muscle_group: 'biceps',
    equipment: 'barbell',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Rest upper arms flat against preacher bench pad.',
      'Curl EZ bar upwards, isolating biceps with zero momentum.',
    ],
    tips: ['Do not hyperextend elbows at the absolute bottom.'],
  },
  {
    id: 'ar-05',
    name: 'Cable Rope Tricep Pushdown',
    category: 'strength',
    muscle_group: 'triceps',
    equipment: 'cable',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Attach rope to high cable. Grip ends with neutral grip.',
      'Push rope down until arms are straight, spreading rope ends apart at the bottom.',
    ],
    tips: ['Flaring the rope at the bottom engages the lateral triceps head.'],
  },
  {
    id: 'ar-06',
    name: 'EZ-Bar Skullcrushers (Lying Triceps Extension)',
    category: 'strength',
    muscle_group: 'triceps',
    equipment: 'barbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Lie on flat bench holding EZ bar overhead.',
      'Bend at elbows only, lowering bar towards forehead or just behind crown.',
      'Extend elbows back to straight arms.',
    ],
    tips: ['Lowering slightly behind the head places greater stretch on the long head.'],
  },
  {
    id: 'ar-07',
    name: 'Overhead Cable Tricep Extension',
    category: 'strength',
    muscle_group: 'triceps',
    secondary_muscles: ['triceps long head'],
    equipment: 'cable',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Facing away from high or low cable, extend rope overhead for deep long head stretch.',
    ],
    tips: ['Overhead position isolates the triceps long head effectively.'],
  },
  {
    id: 'ar-08',
    name: 'Barbell Wrist Curls (Forearm Flexors)',
    category: 'strength',
    muscle_group: 'forearms',
    equipment: 'barbell',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Rest forearms on knees holding barbell with palms facing up.',
      'Curl wrists upward, squeeze flexors, and lower down slowly.',
    ],
    tips: ['Directly thickens the inner forearm flexor bundle.'],
  },
  {
    id: 'ar-09',
    name: 'Reverse Barbell Wrist Curls (Extensors)',
    category: 'strength',
    muscle_group: 'forearms',
    equipment: 'barbell',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Rest forearms on knees holding barbell with palms facing down.',
      'Extend wrists upward contracting outer forearm extensors.',
    ],
    tips: ['Strengthens the wrist extensors and helps prevent tennis elbow.'],
  },

  // ==========================================
  // 7. CALISTHENICS & BODYWEIGHT
  // ==========================================
  {
    id: 'cal-01',
    name: 'Standard Push-Ups',
    category: 'calisthenics',
    muscle_group: 'chest',
    secondary_muscles: ['triceps', 'front delts', 'core'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Place hands slightly wider than shoulder-width, body in a rigid plank.',
      'Lower chest until 2 inches from floor, elbows at 45° angle.',
      'Push floor away back to lockout.',
    ],
    tips: ['Keep glutes clenched and abs braced like a solid iron plank.'],
  },
  {
    id: 'cal-02',
    name: 'Diamond Push-Ups',
    category: 'calisthenics',
    muscle_group: 'triceps',
    secondary_muscles: ['inner chest', 'core'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Form a diamond triangle with thumbs and index fingers under chest.',
      'Lower chest directly to hands and press up.',
    ],
    tips: ['Heavy bodyweight movement for tricep horseshoe development.'],
  },
  {
    id: 'cal-03',
    name: 'Strict Pull-Ups',
    category: 'calisthenics',
    muscle_group: 'back',
    secondary_muscles: ['biceps', 'forearms', 'core'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Hang from bar with overhand grip wider than shoulders.',
      'Depress scapula and pull chest up until chin clears the bar.',
      'Lower under complete control to dead hang.',
    ],
    tips: ['Zero kipping or leg swinging; purely engage lats and mid-back.'],
  },
  {
    id: 'cal-04',
    name: 'Chin-Ups (Underhand Grip)',
    category: 'calisthenics',
    muscle_group: 'biceps',
    secondary_muscles: ['lats', 'upper back'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Grip bar with palms facing you (supinated grip).',
      'Pull chin over bar, pulling elbows down hard to engage biceps and lats.',
    ],
    tips: ['Tremendous compound bicep and lat mass builder.'],
  },
  {
    id: 'cal-05',
    name: 'Bar Muscle-Ups',
    category: 'calisthenics',
    muscle_group: 'full_body',
    secondary_muscles: ['lats', 'chest', 'triceps', 'core'],
    equipment: 'bodyweight',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'From dead hang with false grip, pull explosively toward sternum.',
      'Transition chest rapidly over the bar, pressing out to dip lockout.',
    ],
    tips: ['Requires explosive pull velocity and rapid wrist turnover.'],
  },
  {
    id: 'cal-06',
    name: 'Pike Push-Ups (Shoulder Focus)',
    category: 'calisthenics',
    muscle_group: 'shoulders',
    secondary_muscles: ['triceps', 'upper chest'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Set body in downward V shape with hips elevated.',
      'Lower crown of head diagonally forward between hands, then press back up.',
    ],
    tips: ['The key foundational step toward mastering freestanding handstand pushups.'],
  },
  {
    id: 'cal-07',
    name: 'Handstand Push-Ups (Wall-Assisted)',
    category: 'calisthenics',
    muscle_group: 'shoulders',
    secondary_muscles: ['triceps', 'core'],
    equipment: 'bodyweight',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Kick up into handstand against a solid wall.',
      'Lower head slowly to floor, press upward with explosive shoulder power.',
    ],
    tips: ['Tuck elbows at 45° to avoid impingement.'],
  },
  {
    id: 'cal-08',
    name: 'Parallel Bar Dips',
    category: 'calisthenics',
    muscle_group: 'triceps',
    secondary_muscles: ['chest', 'shoulders'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Suspend body on dip bars with upright posture.',
      'Lower down to 90 degrees elbow bend, press up to top.',
    ],
    tips: ['Keep torso upright to focus on triceps.'],
  },
  {
    id: 'cal-09',
    name: 'Inverted Rows (Australian Pull-ups)',
    category: 'calisthenics',
    muscle_group: 'back',
    secondary_muscles: ['biceps', 'rear delts'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Hang underneath a waist-height bar with heels on floor.',
      'Pull chest up to touch bar, retracting shoulder blades.',
    ],
    tips: ['Great horizontal pulling movement for posture and scapular retraction.'],
  },
  {
    id: 'cal-10',
    name: 'Pistol Squat (Single Leg Squat)',
    category: 'calisthenics',
    muscle_group: 'quads',
    secondary_muscles: ['glutes', 'core', 'balance'],
    equipment: 'bodyweight',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Stand on one leg with opposite leg extended straight forward.',
      'Squat all the way down on single leg, then stand up under control.',
    ],
    tips: ['Requires exceptional ankle dorsiflexion and unilateral quad strength.'],
  },
  {
    id: 'cal-11',
    name: 'Hanging Leg Raises (Core & Abs)',
    category: 'calisthenics',
    muscle_group: 'core',
    secondary_muscles: ['hip flexors', 'grip'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Hang from bar with straight arms.',
      'Raise straight legs up to 90 degrees or touch toes to bar, avoiding body swing.',
    ],
    tips: ['Tilt pelvis upward at the peak to engage the lower rectus abdominis.'],
  },
  {
    id: 'cal-12',
    name: 'Dragon Flag (Bruce Lee Core)',
    category: 'calisthenics',
    muscle_group: 'core',
    secondary_muscles: ['lower back', 'lats'],
    equipment: 'bodyweight',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Lie on bench holding behind head.',
      'Raise entire body straight up like a pillar, lower slowly without bending at waist.',
    ],
    tips: ['Legendary core movement for anti-extension strength.'],
  },
  {
    id: 'cal-13',
    name: 'L-Sit Hold (Parallettes / Floor)',
    category: 'calisthenics',
    muscle_group: 'core',
    secondary_muscles: ['triceps', 'shoulders', 'quads'],
    equipment: 'bodyweight',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Support body on parallettes or floor, extend legs parallel to floor in an L shape and hold.',
    ],
    tips: ['Depress shoulders down into the floor while flexing hip flexors and abs.'],
  },

  // ==========================================
  // 8. OLYMPIC WEIGHTLIFTING
  // ==========================================
  {
    id: 'oly-01',
    name: 'Barbell Snatch',
    category: 'olympic',
    muscle_group: 'full_body',
    secondary_muscles: ['legs', 'shoulders', 'back', 'traps'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Wide hook grip on barbell over mid-foot.',
      'Explosive triple extension (ankles, knees, hips) pulling bar vertically.',
      'Drop swiftly under the bar into a full overhead squat and stand to completion.',
    ],
    tips: ['The fastest barbell movement in the world; speed under the bar is everything.'],
  },
  {
    id: 'oly-02',
    name: 'Clean and Jerk',
    category: 'olympic',
    muscle_group: 'full_body',
    secondary_muscles: ['quads', 'glutes', 'delts', 'triceps'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Clean: pull bar from floor and catch on shoulders in front squat.',
      'Jerk: dip knees and drive bar overhead splitting legs front and back into lockout.',
    ],
    tips: ['Split jerk requires aggressive front foot landing and solid overhead lockout.'],
  },
  {
    id: 'oly-03',
    name: 'Power Clean',
    category: 'olympic',
    muscle_group: 'full_body',
    secondary_muscles: ['traps', 'hamstrings', 'quads', 'back'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Pull bar explosively from floor and catch in a quarter-squat on anterior deltoids.',
      'Stand up tall before lowering bar to floor.',
    ],
    tips: ['Unsurpassed exercise for explosive power output in sprinting and jumping.'],
  },
  {
    id: 'oly-04',
    name: 'Push Press',
    category: 'olympic',
    muscle_group: 'shoulders',
    secondary_muscles: ['quads', 'glutes', 'triceps'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Rack bar on shoulders, dip knees 2-3 inches, drive legs explosively to propel bar overhead.',
    ],
    tips: ['Use lower body momentum to punch bar past the sticking point.'],
  },
  {
    id: 'oly-05',
    name: 'Overhead Squat',
    category: 'olympic',
    muscle_group: 'full_body',
    secondary_muscles: ['shoulders', 'core', 'quads'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Hold bar in wide snatch grip locked overhead.',
      'Squat below parallel keeping bar directly aligned over heels.',
    ],
    tips: ['Demands supreme thoracic mobility, ankle flexibility, and core stability.'],
  },
  {
    id: 'oly-06',
    name: 'Hang Power Snatch',
    category: 'olympic',
    muscle_group: 'full_body',
    secondary_muscles: ['traps', 'hamstrings', 'shoulders'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Start with barbell resting above knees in the hang position.',
      'Extend hips explosively and pull bar directly overhead catching in a power stance.',
    ],
    tips: ['Great for athletes training for vertical jump and rate of force development.'],
  },

  // ==========================================
  // 9. HIIT, CARDIO & METABOLIC
  // ==========================================
  {
    id: 'ht-01',
    name: 'Treadmill Sprint Intervals (HIIT)',
    category: 'hiit',
    muscle_group: 'full_body',
    secondary_muscles: ['legs', 'cardio'],
    equipment: 'cardio_machine',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Sprint at 85-95% max velocity for 30 seconds.',
      'Rest or walk slowly for 60 seconds. Repeat 8-10 rounds.',
    ],
    tips: ['Land on mid-foot with high knee drive and upright posture.'],
  },
  {
    id: 'ht-02',
    name: 'Concept2 Rowing Machine Intervals',
    category: 'hiit',
    muscle_group: 'full_body',
    secondary_muscles: ['back', 'legs', 'core'],
    equipment: 'cardio_machine',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Drive with legs first, lean back with core, pull handle to lower ribs.',
      'Reverse motion smoothly on the recovery.',
    ],
    tips: ['60% leg drive, 20% core lean, 20% arm pull.'],
  },
  {
    id: 'ht-03',
    name: 'Assault AirBike Sprints (Tabata)',
    category: 'hiit',
    muscle_group: 'full_body',
    equipment: 'cardio_machine',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Push and pull handles while pedaling with maximum wattage for 20 seconds.',
      'Rest 10 seconds. Repeat for 8 grueling cycles (4 minutes total).',
    ],
    tips: ['The premier metabolic calorie incinerator.'],
  },
  {
    id: 'ht-04',
    name: 'Speed Jump Rope (Double-Unders)',
    category: 'hiit',
    muscle_group: 'calves',
    secondary_muscles: ['shoulders', 'core', 'cardio'],
    equipment: 'other',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Bounce lightly on balls of feet, turn rope using rapid wrist flick.',
      'For double-unders, spin rope twice beneath feet per jump.',
    ],
    tips: ['Keep elbows tucked close to ribcage.'],
  },
  {
    id: 'ht-05',
    name: 'Battle Ropes (Alternating Waves & Slams)',
    category: 'hiit',
    muscle_group: 'shoulders',
    secondary_muscles: ['arms', 'core', 'cardio'],
    equipment: 'other',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Hold heavy ropes, bend knees in athletic stance, create rapid alternating vertical waves.',
      'Perform overhead double slams for max power output.',
    ],
    tips: ['Brace core tight and do not let upper body rock back and forth.'],
  },
  {
    id: 'ht-06',
    name: 'Plyometric Box Jumps (30-Inch)',
    category: 'hiit',
    muscle_group: 'quads',
    secondary_muscles: ['calves', 'glutes', 'explosiveness'],
    equipment: 'other',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Stand facing plyo box. Swing arms, jump explosively and land softly on top.',
      'Step down one foot at a time to protect Achilles tendons.',
    ],
    tips: ['Land softly like a cat absorbing the impact with bent knees.'],
  },
  {
    id: 'ht-07',
    name: 'Burpees (Chest to Floor)',
    category: 'hiit',
    muscle_group: 'full_body',
    secondary_muscles: ['chest', 'quads', 'core'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Drop hands to floor, jump feet back, lower chest to ground, jump feet forward and leap vertically with clap.',
    ],
    tips: ['Pace your breathing rhythm to sustain long intervals.'],
  },
  {
    id: 'ht-08',
    name: 'Mountain Climbers (High Speed)',
    category: 'hiit',
    muscle_group: 'core',
    secondary_muscles: ['shoulders', 'cardio'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'In high plank position, drive knees alternately toward chest in a rapid running motion.',
    ],
    tips: ['Keep hips level with shoulders; avoid piking hips in the air.'],
  },

  // ==========================================
  // 10. FUNCTIONAL & CROSSFIT
  // ==========================================
  {
    id: 'fn-01',
    name: 'Kettlebell Swings (Hardstyle Russian)',
    category: 'functional',
    muscle_group: 'hamstrings',
    secondary_muscles: ['glutes', 'lower back', 'shoulders'],
    equipment: 'kettlebell',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Hinge at hips with kettlebell between legs.',
      'Snap hips forward violently with glute clench to float kettlebell to chest height.',
      'Let gravity bring bell down, guide into next hinge cycle.',
    ],
    tips: ['It is a hip hinge, NOT a squat. Arms are merely ropes guiding the bell.'],
  },
  {
    id: 'fn-02',
    name: 'Barbell Thrusters',
    category: 'functional',
    muscle_group: 'full_body',
    secondary_muscles: ['quads', 'shoulders', 'core'],
    equipment: 'barbell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Perform a deep front squat, then use the leg drive to immediately press the bar overhead in one fluid motion.',
    ],
    tips: ['The hallmark CrossFit movement blending squatting leg power with overhead pressing.'],
  },
  {
    id: 'fn-03',
    name: 'Wall Ball Shots (20 lb)',
    category: 'functional',
    muscle_group: 'full_body',
    secondary_muscles: ['quads', 'shoulders'],
    equipment: 'other',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Hold medicine ball at chest, squat deep, stand up explosively and throw ball at 10-foot wall target.',
    ],
    tips: ['Catch the ball on the descent directly into the next squat.'],
  },
  {
    id: 'fn-04',
    name: 'Heavy Prowler Sled Push',
    category: 'functional',
    muscle_group: 'quads',
    secondary_muscles: ['calves', 'glutes', 'core'],
    equipment: 'other',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Grip high sled poles, drive legs forward with strong forward 45° torso angle.',
    ],
    tips: ['Zero eccentric muscle damage allows frequent heavy sprint workouts.'],
  },
  {
    id: 'fn-05',
    name: 'Heavy Farmer’s Walk (Loaded Carries)',
    category: 'functional',
    muscle_group: 'forearms',
    secondary_muscles: ['traps', 'core', 'glutes'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Pick up heavy dumbbells or trap bar, walk with tall posture and short rapid steps.',
    ],
    tips: ['Builds unbreakable grip, massive upper traps, and core stability.'],
  },
  {
    id: 'fn-06',
    name: 'Turkish Get-Up (Full 7-Step Protocol)',
    category: 'functional',
    muscle_group: 'full_body',
    secondary_muscles: ['shoulders', 'core', 'mobility'],
    equipment: 'kettlebell',
    difficulty: 'advanced',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'From lying on back with kettlebell pressed overhead, move through elbow, hand, bridge, sweep, lunge to full stand while keeping arm vertical.',
    ],
    tips: ['Keep eyes locked on the kettlebell at all times.'],
  },

  // ==========================================
  // 11. YOGA, PILATES & MOBILITY
  // ==========================================
  {
    id: 'yg-01',
    name: 'Sun Salutation Flow (Surya Namaskar)',
    category: 'yoga_mobility',
    muscle_group: 'full_body',
    equipment: 'bodyweight',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Flow through Mountain Pose, Forward Fold, Halfway Lift, Plank, Chaturanga, Upward Dog, and Downward Dog.',
    ],
    tips: ['Synchronize every movement with deep diaphragmatic nasal breathing.'],
  },
  {
    id: 'yg-02',
    name: 'Pigeon Pose (Deep Hip Opener)',
    category: 'yoga_mobility',
    muscle_group: 'glutes',
    secondary_muscles: ['hip flexors', 'lower back'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'From plank, bring right knee behind right wrist, extend left leg back and lower hips.',
      'Fold upper body forward over the front shin to deepen glute and piriformis stretch.',
    ],
    tips: ['Keep hips square to floor without rolling onto one side.'],
  },
  {
    id: 'yg-03',
    name: 'World’s Greatest Stretch (Thoracic Rotation)',
    category: 'yoga_mobility',
    muscle_group: 'full_body',
    secondary_muscles: ['thoracic spine', 'hip flexors', 'hamstrings'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Step into a deep lunge, place hands inside front foot, rotate torso and reach top arm to ceiling.',
    ],
    tips: ['The gold standard warm-up drill for athletes worldwide.'],
  },
  {
    id: 'yg-04',
    name: '90/90 Hip Mobility Flow',
    category: 'yoga_mobility',
    muscle_group: 'glutes',
    secondary_muscles: ['hips', 'adductors'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Sit with both knees bent at 90 degrees on floor, rotate knees side to side without using hands.',
    ],
    tips: ['Builds internal and external hip rotation for deeper squats.'],
  },
  {
    id: 'yg-05',
    name: 'Cat-Cow Spinal Mobility',
    category: 'yoga_mobility',
    muscle_group: 'back',
    secondary_muscles: ['core', 'neck'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'On all fours, alternate between arching back and looking up (Cow) and rounding spine tucking chin (Cat).',
    ],
    tips: ['Restores segmental spinal articulation.'],
  },
  {
    id: 'yg-06',
    name: 'Couch Stretch (Deep Quad & Hip Flexor)',
    category: 'yoga_mobility',
    muscle_group: 'quads',
    secondary_muscles: ['hip flexors', 'psoas'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Back shin placed vertically against wall, front foot in lunge, squeeze glutes and raise torso upright.',
    ],
    tips: ['Relieves anterior pelvic tilt and lower back tightness caused by sitting.'],
  },

  // ==========================================
  // 12. COMBAT & BOXING CONDITIONING
  // ==========================================
  {
    id: 'cb-01',
    name: 'Shadow Boxing (3-Min Championship Rounds)',
    category: 'combat',
    muscle_group: 'full_body',
    secondary_muscles: ['shoulders', 'core', 'cardio'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Adopt boxing stance, chin down, hands guarding cheeks.',
      'Throw combinations: Jab-Cross-Hook-Uppercut with head movement (slips, rolls) and footwork pivoting.',
    ],
    tips: ['Rotate through the hips on every punch to generate power.'],
  },
  {
    id: 'cb-02',
    name: 'Heavy Bag Power Strikes & Combinations',
    category: 'combat',
    muscle_group: 'full_body',
    secondary_muscles: ['chest', 'shoulders', 'legs'],
    equipment: 'other',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Deliver combinations with maximum rotational hip torque on heavy punching bag.',
      'Circle the bag constantly and maintain defensive guard after throwing.',
    ],
    tips: ['Wrap your hands properly to protect metacarpal bones.'],
  },
  {
    id: 'cb-03',
    name: 'Speed Bag Rhythm Drill',
    category: 'combat',
    muscle_group: 'shoulders',
    secondary_muscles: ['forearms', 'coordination'],
    equipment: 'other',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Maintain continuous 3-beat rebound tempo on speed bag keeping hands high at chin level.',
    ],
    tips: ['Builds shoulder endurance and hand-eye hand velocity.'],
  },
  {
    id: 'cb-04',
    name: 'Thai Clinch Knee Strikes',
    category: 'combat',
    muscle_group: 'core',
    secondary_muscles: ['glutes', 'hip flexors', 'cardio'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Simulate Thai plum neck clinch, pull down while driving hip and knee spear forward.',
    ],
    tips: ['Extend hips forward at impact for maximum penetrating force.'],
  },
  {
    id: 'cb-05',
    name: 'Sprawl & Jab Reaction Drill',
    category: 'combat',
    muscle_group: 'full_body',
    secondary_muscles: ['legs', 'chest', 'cardio'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    image_url: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Throw 1-2 punch combo, drop hips to floor in wrestling sprawl to defend takedown, pop up immediately and throw 2-3 punches.',
    ],
    tips: ['Essential MMA conditioning drill for fast level-changes.'],
  },

  // ==========================================
  // 13. HOME & MINIMAL GEAR
  // ==========================================
  {
    id: 'hm-01',
    name: 'Banded Shoulder Overhead Press',
    category: 'home',
    muscle_group: 'shoulders',
    secondary_muscles: ['triceps', 'upper chest'],
    equipment: 'bands',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Stand on resistance band loop with feet shoulder-width.',
      'Press handles or ends overhead with steady band resistance.',
    ],
    tips: ['Band resistance increases at top lockout where your delts are strongest.'],
  },
  {
    id: 'hm-02',
    name: 'Banded Bicep Curls',
    category: 'home',
    muscle_group: 'biceps',
    secondary_muscles: ['forearms'],
    equipment: 'bands',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Anchor band under feet and curl upward against progressive resistance.',
    ],
    tips: ['Squeeze hard at top where band is under highest tension.'],
  },
  {
    id: 'hm-03',
    name: 'Chair / Bedside Tricep Dips',
    category: 'home',
    muscle_group: 'triceps',
    secondary_muscles: ['chest', 'front delts'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Place hands on edge of sturdy chair with legs extended out front.',
      'Lower hips down, bend elbows to 90 degrees, and press up.',
    ],
    tips: ['Elevate feet on a second chair to increase difficulty.'],
  },
  {
    id: 'hm-04',
    name: 'Backpack Loaded Squats',
    category: 'home',
    muscle_group: 'quads',
    secondary_muscles: ['glutes', 'core'],
    equipment: 'other',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Fill a sturdy backpack with books or water bottles, wear on back or hug to chest (goblet style).',
      'Squat deep with proud chest, press through floor to stand.',
    ],
    tips: ['Hug to chest as a goblet squat for better core activation and upright posture.'],
  },
  {
    id: 'hm-05',
    name: 'Single-Leg Floor Glute Bridge',
    category: 'home',
    muscle_group: 'glutes',
    secondary_muscles: ['hamstrings', 'core'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Lie on back with knees bent. Extend one leg straight in air.',
      'Drive through opposite heel to lift hips into straight line, squeezing glute at top.',
    ],
    tips: ['Hold for 2 seconds at top; excellent glute activator with no gear.'],
  },
  {
    id: 'hm-06',
    name: 'Doorway Isometric Lat Rows (Towel Drill)',
    category: 'home',
    muscle_group: 'back',
    secondary_muscles: ['biceps', 'rear delts'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    instructions: [
      'Loop a strong towel around a doorframe or post.',
      'Lean back with straight arms and row your body up by driving elbows back.',
    ],
    tips: ['Adjust foot angle closer to door to increase resistance.'],
  },
];

// Curated Ready-to-Launch Training Programs
export const CURATED_WORKOUT_PROGRAMS: WorkoutTemplate[] = [
  {
    id: 'prog-ppl-push',
    title: 'Push Power & Hypertrophy',
    category: 'Strength Split',
    duration_min: 50,
    level: 'Intermediate',
    description: 'Target chest, front/lateral delts, and triceps with heavy compounds followed by isolation burnouts.',
    icon: 'activity',
    exercises: [
      { exercise_id: 'ch-01', exercise_name: 'Barbell Flat Bench Press', target_sets: 4, target_reps: '6-8', muscle_group: 'chest' },
      { exercise_id: 'ch-02', exercise_name: 'Incline Dumbbell Press', target_sets: 3, target_reps: '8-10', muscle_group: 'chest' },
      { exercise_id: 'sh-01', exercise_name: 'Standing Barbell Overhead Press (OHP)', target_sets: 3, target_reps: '8', muscle_group: 'shoulders' },
      { exercise_id: 'sh-04', exercise_name: 'Standing Dumbbell Lateral Raise', target_sets: 4, target_reps: '12-15', muscle_group: 'shoulders' },
      { exercise_id: 'ar-05', exercise_name: 'Cable Rope Tricep Pushdown', target_sets: 3, target_reps: '12', muscle_group: 'triceps' },
      { exercise_id: 'ar-06', exercise_name: 'EZ-Bar Skullcrushers', target_sets: 3, target_reps: '10', muscle_group: 'triceps' },
    ],
  },
  {
    id: 'prog-ppl-pull',
    title: 'Pull Power & Lat Width',
    category: 'Strength Split',
    duration_min: 55,
    level: 'Intermediate',
    description: 'Thick upper back, V-taper lats, rear deltoids, and peak bicep recruitment.',
    icon: 'shield',
    exercises: [
      { exercise_id: 'pl-06', exercise_name: 'Conventional Barbell Deadlift', target_sets: 3, target_reps: '5', muscle_group: 'back' },
      { exercise_id: 'cal-03', exercise_name: 'Strict Pull-Ups', target_sets: 4, target_reps: '8-10', muscle_group: 'back' },
      { exercise_id: 'bk-02', exercise_name: 'Barbell Bent-Over Row', target_sets: 3, target_reps: '8-10', muscle_group: 'back' },
      { exercise_id: 'bk-08', exercise_name: 'Face Pulls (Cable Rope)', target_sets: 4, target_reps: '15', muscle_group: 'shoulders' },
      { exercise_id: 'ar-01', exercise_name: 'Standing Barbell Bicep Curl', target_sets: 3, target_reps: '10', muscle_group: 'biceps' },
      { exercise_id: 'ar-03', exercise_name: 'Dumbbell Hammer Curls', target_sets: 3, target_reps: '12', muscle_group: 'biceps' },
    ],
  },
  {
    id: 'prog-ppl-legs',
    title: 'Legs & Core Domination',
    category: 'Strength Split',
    duration_min: 50,
    level: 'Advanced',
    description: 'Heavy squats, Romanian deadlifts, glute development, and core stability.',
    icon: 'zap',
    exercises: [
      { exercise_id: 'pl-01', exercise_name: 'Competition Barbell Squat', target_sets: 4, target_reps: '6-8', muscle_group: 'quads' },
      { exercise_id: 'lg-04', exercise_name: 'Romanian Deadlift (RDL)', target_sets: 3, target_reps: '8-10', muscle_group: 'hamstrings' },
      { exercise_id: 'lg-06', exercise_name: 'Bulgarian Split Squat', target_sets: 3, target_reps: '10 / leg', muscle_group: 'quads' },
      { exercise_id: 'lg-03', exercise_name: 'Barbell Hip Thrust', target_sets: 3, target_reps: '10-12', muscle_group: 'glutes' },
      { exercise_id: 'lg-10', exercise_name: 'Standing Calf Raises', target_sets: 4, target_reps: '15', muscle_group: 'calves' },
      { exercise_id: 'cal-11', exercise_name: 'Hanging Leg Raises', target_sets: 3, target_reps: '15', muscle_group: 'core' },
    ],
  },
  {
    id: 'prog-powerlifting-big3',
    title: 'Powerlifting Big 3 Peak Protocol',
    category: 'Powerlifting',
    duration_min: 65,
    level: 'Advanced',
    description: 'Heavy strength development focused purely on the competition Squat, Bench Press, and Deadlift.',
    icon: 'shield',
    exercises: [
      { exercise_id: 'pl-01', exercise_name: 'Competition Barbell Squat', target_sets: 5, target_reps: '3-5', muscle_group: 'quads' },
      { exercise_id: 'pl-03', exercise_name: 'Competition Paused Bench Press', target_sets: 5, target_reps: '3-5', muscle_group: 'chest' },
      { exercise_id: 'pl-06', exercise_name: 'Conventional Barbell Deadlift', target_sets: 4, target_reps: '3', muscle_group: 'back' },
      { exercise_id: 'pl-05', exercise_name: 'Close-Grip Barbell Bench Press', target_sets: 3, target_reps: '6-8', muscle_group: 'triceps' },
    ],
  },
  {
    id: 'prog-calisthenics-beast',
    title: 'Calisthenics Beast Protocol',
    category: 'Bodyweight Mastery',
    duration_min: 40,
    level: 'Intermediate',
    description: 'Pure relative bodyweight strength, gymnastic control, and solid core.',
    icon: 'award',
    exercises: [
      { exercise_id: 'cal-03', exercise_name: 'Strict Pull-Ups', target_sets: 4, target_reps: '8-12', muscle_group: 'back' },
      { exercise_id: 'cal-08', exercise_name: 'Parallel Bar Dips', target_sets: 4, target_reps: '12-15', muscle_group: 'triceps' },
      { exercise_id: 'cal-01', exercise_name: 'Standard Push-Ups', target_sets: 3, target_reps: '20', muscle_group: 'chest' },
      { exercise_id: 'cal-09', exercise_name: 'Inverted Rows', target_sets: 3, target_reps: '12', muscle_group: 'back' },
      { exercise_id: 'cal-10', exercise_name: 'Pistol Squat', target_sets: 3, target_reps: '6-8 / leg', muscle_group: 'quads' },
      { exercise_id: 'cal-13', exercise_name: 'L-Sit Hold', target_sets: 3, target_reps: '20 sec', muscle_group: 'core' },
    ],
  },
  {
    id: 'prog-combat-boxing',
    title: 'Fighter Conditioning & Power Strikes',
    category: 'Combat & Boxing',
    duration_min: 35,
    level: 'Intermediate',
    description: 'Rounds of heavy bag, shadow boxing footwork, speed drills, and combat core rotation.',
    icon: 'target',
    exercises: [
      { exercise_id: 'cb-01', exercise_name: 'Shadow Boxing', target_sets: 3, target_reps: '3 mins', muscle_group: 'full_body' },
      { exercise_id: 'cb-02', exercise_name: 'Heavy Bag Power Strikes', target_sets: 4, target_reps: '3 mins', muscle_group: 'full_body' },
      { exercise_id: 'cb-05', exercise_name: 'Sprawl & Jab Reaction Drill', target_sets: 3, target_reps: '15', muscle_group: 'full_body' },
      { exercise_id: 'ht-04', exercise_name: 'Speed Jump Rope', target_sets: 3, target_reps: '2 mins', muscle_group: 'calves' },
      { exercise_id: 'cal-11', exercise_name: 'Hanging Leg Raises', target_sets: 3, target_reps: '15', muscle_group: 'core' },
    ],
  },
  {
    id: 'prog-hiit-burner',
    title: '20-Min Metabolic Fat Shred',
    category: 'HIIT & Conditioning',
    duration_min: 20,
    level: 'Beginner',
    description: 'High-intensity interval circuit designed for calorie burn and cardiovascular endurance.',
    icon: 'trending-up',
    exercises: [
      { exercise_id: 'ht-07', exercise_name: 'Burpees (Chest to Floor)', target_sets: 4, target_reps: '15', muscle_group: 'full_body' },
      { exercise_id: 'fn-01', exercise_name: 'Kettlebell Swings', target_sets: 4, target_reps: '20', muscle_group: 'hamstrings' },
      { exercise_id: 'ht-08', exercise_name: 'Mountain Climbers', target_sets: 4, target_reps: '30 sec', muscle_group: 'core' },
      { exercise_id: 'ht-04', exercise_name: 'Speed Jump Rope', target_sets: 4, target_reps: '60 sec', muscle_group: 'calves' },
      { exercise_id: 'ht-06', exercise_name: 'Plyometric Box Jumps', target_sets: 4, target_reps: '12', muscle_group: 'quads' },
    ],
  },
  {
    id: 'prog-home-zero-gear',
    title: 'Zero-Equipment Home Workout',
    category: 'Home Fitness',
    duration_min: 25,
    level: 'Beginner',
    description: 'Full-body workout you can perform anywhere in your room with no gym needed.',
    icon: 'home',
    exercises: [
      { exercise_id: 'cal-01', exercise_name: 'Standard Push-Ups', target_sets: 4, target_reps: '15-20', muscle_group: 'chest' },
      { exercise_id: 'hm-04', exercise_name: 'Backpack Loaded Squats', target_sets: 4, target_reps: '15', muscle_group: 'quads' },
      { exercise_id: 'hm-03', exercise_name: 'Chair / Bedside Tricep Dips', target_sets: 3, target_reps: '12-15', muscle_group: 'triceps' },
      { exercise_id: 'hm-05', exercise_name: 'Single-Leg Floor Glute Bridge', target_sets: 3, target_reps: '12 / leg', muscle_group: 'glutes' },
      { exercise_id: 'cal-02', exercise_name: 'Diamond Push-Ups', target_sets: 3, target_reps: '10', muscle_group: 'triceps' },
    ],
  },
  {
    id: 'prog-mobility-reset',
    title: 'Daily Mobility & Posture Reset',
    category: 'Recovery & Flexibility',
    duration_min: 15,
    level: 'Beginner',
    description: 'Relieve lower back tightness, open up tight hips, and improve shoulder thoracic spine extension.',
    icon: 'sun',
    exercises: [
      { exercise_id: 'yg-01', exercise_name: 'Sun Salutation Flow', target_sets: 3, target_reps: 'Flow', muscle_group: 'full_body' },
      { exercise_id: 'yg-03', exercise_name: 'World’s Greatest Stretch', target_sets: 2, target_reps: '5 / side', muscle_group: 'full_body' },
      { exercise_id: 'yg-04', exercise_name: '90/90 Hip Mobility Flow', target_sets: 2, target_reps: '10 rotations', muscle_group: 'glutes' },
      { exercise_id: 'yg-02', exercise_name: 'Pigeon Pose', target_sets: 2, target_reps: '60 sec / side', muscle_group: 'glutes' },
      { exercise_id: 'yg-05', exercise_name: 'Cat-Cow Spinal Mobility', target_sets: 2, target_reps: '10 breaths', muscle_group: 'back' },
      { exercise_id: 'yg-06', exercise_name: 'Couch Stretch', target_sets: 2, target_reps: '45 sec / leg', muscle_group: 'quads' },
    ],
  },
];
