export type DietType = 
  | 'all' 
  | 'veg' 
  | 'non_veg' 
  | 'vegan' 
  | 'keto' 
  | 'high_protein' 
  | 'desi' 
  | 'mediterranean'
  | 'halal';

export type MealCategory = 
  | 'all' 
  | 'breakfast' 
  | 'lunch' 
  | 'dinner' 
  | 'snack' 
  | 'pre_post_workout';

export interface ServingOption {
  label: string;
  weightGrams: number;
  multiplier: number;
}

export interface FoodItem {
  id: string;
  name: string;
  diet_type: 'veg' | 'non_veg' | 'vegan' | 'keto' | 'high_protein' | 'desi' | 'mediterranean';
  is_halal: boolean;
  category: 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'pre_post_workout';
  calories_per_100g: number;
  protein_g: number; // per 100g
  carbs_g: number;   // per 100g
  fat_g: number;     // per 100g
  fiber_g?: number;  // per 100g
  standard_serving_grams: number;
  serving_options: ServingOption[];
  image_url: string;
  recipe_video_url?: string;
  prep_time_min: number;
  ingredients: string[];
  cooking_steps: string[];
  health_benefits: string[];
}

export interface DietCategoryMeta {
  id: DietType;
  name: string;
  icon: string;
  color: string;
  desc: string;
}

export interface MealCategoryMeta {
  id: MealCategory;
  name: string;
  icon: string;
  timeRange: string;
}

export const DIET_CATEGORIES: DietCategoryMeta[] = [
  { id: 'all', name: 'ALL DIETS', icon: 'infinite', color: '#c3f400', desc: 'Complete global nutrition library' },
  { id: 'veg', name: 'VEGETARIAN', icon: 'leaf', color: '#10b981', desc: 'Lacto & Ovo plant-forward nutrition' },
  { id: 'non_veg', name: 'NON-VEG', icon: 'restaurant', color: '#ef4444', desc: 'Poultry, lean meats & seafood' },
  { id: 'vegan', name: '100% VEGAN', icon: 'nutrition', color: '#06b6d4', desc: '100% plant-powered clean fuel' },
  { id: 'keto', name: 'KETO / LOW-CARB', icon: 'flame', color: '#f59e0b', desc: 'High healthy fat, sub-20g carbs' },
  { id: 'high_protein', name: 'HIGH PROTEIN', icon: 'barbell', color: '#c3f400', desc: '30g-60g muscle-building meals' },
  { id: 'desi', name: 'DESI / SOUTH ASIAN', icon: 'sparkles', color: '#ec4899', desc: 'Healthy traditional subcontinent meals' },
  { id: 'mediterranean', name: 'MEDITERRANEAN', icon: 'heart', color: '#38bdf8', desc: 'Heart-healthy olive oil & seafood' },
  { id: 'halal', name: 'HALAL CERTIFIED', icon: 'shield-checkmark', color: '#10b981', desc: '100% Zabiha & pure clean ingredients' },
];

export const MEAL_CATEGORIES: MealCategoryMeta[] = [
  { id: 'all', name: 'ALL MEALS', icon: 'fast-food-outline', timeRange: 'Anytime' },
  { id: 'breakfast', name: 'BREAKFAST', icon: 'sunny-outline', timeRange: '6:00 AM - 10:30 AM' },
  { id: 'lunch', name: 'LUNCH', icon: 'restaurant-outline', timeRange: '12:00 PM - 3:00 PM' },
  { id: 'dinner', name: 'DINNER', icon: 'moon-outline', timeRange: '7:00 PM - 10:00 PM' },
  { id: 'snack', name: 'SNACKS', icon: 'cafe-outline', timeRange: 'Between Meals' },
  { id: 'pre_post_workout', name: 'WORKOUT FUEL', icon: 'flash-outline', timeRange: 'Pre & Post Lift' },
];

export function getFoodRecipeVideoUrl(food: FoodItem): string {
  if (food.recipe_video_url) return food.recipe_video_url;
  const query = encodeURIComponent(`healthy ${food.name} recipe how to cook`);
  return `https://www.youtube.com/results?search_query=${query}`;
}

// Universal Comprehensive Food and Recipe Database
export const UNIVERSAL_FOOD_DATABASE: FoodItem[] = [
  // =========================================================================
  // 1. NON-VEGETARIAN (Complete: Breakfast, Lunch, Dinner, Snack, Workout)
  // =========================================================================
  {
    id: 'food-nv-bf-01',
    name: 'Boiled Eggs & Avocado Sourdough Toast',
    diet_type: 'non_veg',
    is_halal: true,
    category: 'breakfast',
    calories_per_100g: 185,
    protein_g: 11,
    carbs_g: 14,
    fat_g: 10,
    fiber_g: 4,
    standard_serving_grams: 220,
    serving_options: [
      { label: '1 Slice + 1 Egg (110g)', weightGrams: 110, multiplier: 1.1 },
      { label: '2 Slices + 2 Eggs (220g)', weightGrams: 220, multiplier: 2.2 },
    ],
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 10,
    ingredients: ['2 Multigrain / Sourdough Slices', '2 Pasture-Raised Eggs', '1/2 Ripe Hass Avocado', 'Chili Flakes', 'Lemon Juice'],
    cooking_steps: [
      'Boil eggs in bubbling water for 7 minutes for a medium-jammy yolk.',
      'Toast artisan sourdough bread until golden brown.',
      'Mash avocado with fresh lemon juice and sea salt; spread across toast.',
      'Halve boiled eggs, place on avocado toast, and garnish with red chili flakes.',
    ],
    health_benefits: ['Complete amino acid spectrum for muscle protein synthesis', 'Monounsaturated oleic acid regulates cholesterol', 'Slow-burning carbs for steady morning energy'],
  },
  {
    id: 'food-nv-bf-02',
    name: 'Smoked Salmon & Poached Eggs on Whole Rye',
    diet_type: 'non_veg',
    is_halal: true,
    category: 'breakfast',
    calories_per_100g: 170,
    protein_g: 15,
    carbs_g: 11,
    fat_g: 7.5,
    fiber_g: 2.5,
    standard_serving_grams: 200,
    serving_options: [
      { label: '1 Serving (200g)', weightGrams: 200, multiplier: 2.0 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Lox_on_Bagel%2C_Atlanta_GA.jpg/960px-Lox_on_Bagel%2C_Atlanta_GA.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 12,
    ingredients: ['Wild Smoked Salmon (70g)', '2 Poached Eggs', 'Whole Rye Toast (1 slice)', 'Fresh Dill & Capers', 'Lemon Juice'],
    cooking_steps: [
      'Poach fresh eggs in simmering water with 1 tsp vinegar for 3 minutes.',
      'Layer premium smoked salmon ribbons over warm whole rye toast.',
      'Top with warm poached eggs, cracked black pepper, and fresh dill sprigs.',
    ],
    health_benefits: ['EPA/DHA Omega-3s reduce resting heart rate and arterial inflammation', 'Choline boosts neural transmitter focus', 'Zero refined oils'],
  },
  {
    id: 'food-nv-ln-01',
    name: 'Grilled Lemon Herb Chicken Breast',
    diet_type: 'non_veg',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 165,
    protein_g: 31,
    carbs_g: 0,
    fat_g: 3.6,
    fiber_g: 0,
    standard_serving_grams: 200,
    serving_options: [
      { label: '100g Portion', weightGrams: 100, multiplier: 1 },
      { label: 'Medium Breast (200g)', weightGrams: 200, multiplier: 2 },
      { label: 'Large Breast (300g)', weightGrams: 300, multiplier: 3 },
    ],
    image_url: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 20,
    ingredients: ['Skinless Chicken Breast (200g)', 'Olive Oil (1 tsp)', 'Lemon Juice', 'Garlic Powder', 'Dried Oregano', 'Sea Salt & Pepper'],
    cooking_steps: [
      'Pound chicken breast to even 1/2 inch thickness for uniform cooking.',
      'Marinate in olive oil, fresh lemon juice, crushed garlic, and oregano for 15 mins.',
      'Sear on hot grill pan for 6-7 minutes per side until 74°C internal temperature.',
      'Rest for 5 minutes before slicing to lock in all natural juices.',
    ],
    health_benefits: ['Lean bioavailable protein for myofibrillar repair', 'Rich in Niacin (Vitamin B3) for energy metabolism', 'Near-zero carbohydrate impact for lean cutting'],
  },
  {
    id: 'food-nv-ln-02',
    name: 'Albacore Tuna & Mixed Green Salad',
    diet_type: 'non_veg',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 110,
    protein_g: 18,
    carbs_g: 3.2,
    fat_g: 2.8,
    fiber_g: 1.8,
    standard_serving_grams: 280,
    serving_options: [
      { label: 'Standard Bowl (280g)', weightGrams: 280, multiplier: 2.8 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Nizza-Salat_an_der_F_Mittelmeerk%C3%BCste.JPG/960px-Nizza-Salat_an_der_F_Mittelmeerk%C3%BCste.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 8,
    ingredients: ['Chunk Light Tuna in Water (150g drained)', 'Mixed Greens & Arugula', 'Cherry Tomatoes', 'Cucumbers', 'Dijon Mustard Vinaigrette'],
    cooking_steps: [
      'Toss crisp greens, halved cherry tomatoes, and sliced cucumber in a wide bowl.',
      'Flake drained albacore tuna over the greens.',
      'Drizzle with light Dijon mustard, lemon, and 1 tsp extra virgin olive oil.',
    ],
    health_benefits: ['Ultra-high protein density per calorie', 'Abundant Selenium for thyroid support', 'Light and crisp for midday alertness'],
  },
  {
    id: 'food-nv-dn-01',
    name: 'Pan-Seared Atlantic Salmon Fillet',
    diet_type: 'non_veg',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 208,
    protein_g: 22,
    carbs_g: 0,
    fat_g: 13,
    fiber_g: 0,
    standard_serving_grams: 180,
    serving_options: [
      { label: '100g Portion', weightGrams: 100, multiplier: 1 },
      { label: '1 Fillet (180g)', weightGrams: 180, multiplier: 1.8 },
      { label: 'King Fillet (250g)', weightGrams: 250, multiplier: 2.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 15,
    ingredients: ['Fresh Salmon Fillet (180g)', 'Extra Virgin Olive Oil', 'Dill Weed', 'Lemon Wedges', 'Coarse Himalayan Salt'],
    cooking_steps: [
      'Pat salmon skin completely dry with paper towels to ensure crispy skin.',
      'Season generously with salt, cracked pepper, and fresh dill.',
      'Place skin-side down in a hot non-stick pan with 1/2 tsp oil for 5 minutes without moving.',
      'Flip gently and cook for another 3 minutes until medium-rare tender.',
    ],
    health_benefits: ['Abundant in EPA & DHA Omega-3 fatty acids for joint and heart health', 'Supports brain cognition and lowers systemic inflammation', 'High Vitamin D for bone density'],
  },
  {
    id: 'food-nv-dn-02',
    name: 'Garlic Butter Prawns & Steamed Asparagus',
    diet_type: 'non_veg',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 110,
    protein_g: 21,
    carbs_g: 2,
    fat_g: 2.1,
    fiber_g: 1.0,
    standard_serving_grams: 250,
    serving_options: [
      { label: '100g Prawn Portion', weightGrams: 100, multiplier: 1 },
      { label: 'Full Plate (250g)', weightGrams: 250, multiplier: 2.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1559742811-822873691df8?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 12,
    ingredients: ['Fresh Jumbo Prawns (200g)', 'Fresh Asparagus spears (100g)', 'Garlic (3 cloves minced)', 'Grass-fed Butter (5g)', 'Parsley'],
    cooking_steps: [
      'Steam asparagus spears for 4 minutes until bright green and crisp.',
      'Melt butter in a skillet, add minced garlic and sauté for 30 seconds.',
      'Add deveined prawns and cook on high heat for 2 minutes per side until pink.',
      'Toss with steamed asparagus, fresh lemon juice, and chopped parsley.',
    ],
    health_benefits: ['Extremely high protein-to-calorie ratio', 'Loaded with Selenium and Vitamin B12', 'Asparagus provides prebiotic inulin fiber'],
  },
  {
    id: 'food-nv-sn-01',
    name: 'Hard-Boiled Organic Eggs with Sea Salt',
    diet_type: 'non_veg',
    is_halal: true,
    category: 'snack',
    calories_per_100g: 155,
    protein_g: 13,
    carbs_g: 1.1,
    fat_g: 11,
    fiber_g: 0,
    standard_serving_grams: 100,
    serving_options: [
      { label: '2 Large Eggs (100g)', weightGrams: 100, multiplier: 1.0 },
      { label: '3 Large Eggs (150g)', weightGrams: 150, multiplier: 1.5 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/Soft-boiled-egg.jpg/960px-Soft-boiled-egg.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 9,
    ingredients: ['2 Pasture Eggs', 'Sea Salt', 'Black Pepper', 'Paprika pinch'],
    cooking_steps: [
      'Place eggs in boiling water for 8.5 minutes.',
      'Transfer immediately into an ice bath for 3 minutes for effortless peeling.',
      'Peel, slice in half, and season with coarse salt and smoked paprika.',
    ],
    health_benefits: ['Quick, portable zero-prep complete protein snack', 'High Lutein and Zeaxanthin', 'Steady blood sugar stabilization'],
  },
  {
    id: 'food-nv-wo-01',
    name: 'Seared Chicken Strips & Sweet Potato Mash',
    diet_type: 'non_veg',
    is_halal: true,
    category: 'pre_post_workout',
    calories_per_100g: 140,
    protein_g: 18,
    carbs_g: 15,
    fat_g: 1.5,
    fiber_g: 2.2,
    standard_serving_grams: 300,
    serving_options: [
      { label: 'Standard Box (300g)', weightGrams: 300, multiplier: 3.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 20,
    ingredients: ['Chicken Breast Strips (180g)', 'Boiled Sweet Potato (120g)', 'Cinnamon', 'Sea Salt'],
    cooking_steps: [
      'Pan-sear seasoned chicken tenderloin strips for 3 minutes per side.',
      'Mash steamed sweet potato with a pinch of cinnamon and pink salt.',
      'Pair together for the premier clean bodybuilding post-workout recovery meal.',
    ],
    health_benefits: ['Fast glycogen resynthesis with zero digestive burden', 'Complex potassium replenishment prevents cramps', 'High leucine triggers muscle protein synthesis'],
  },

  // =========================================================================
  // 2. HIGH PROTEIN / BODYBUILDING (Complete All 5 Subcategories)
  // =========================================================================
  {
    id: 'food-hp-bf-01',
    name: 'Egg White & Turkey Bacon Herb Frittata',
    diet_type: 'high_protein',
    is_halal: true,
    category: 'breakfast',
    calories_per_100g: 110,
    protein_g: 16,
    carbs_g: 2.5,
    fat_g: 3.8,
    fiber_g: 0.8,
    standard_serving_grams: 250,
    serving_options: [
      { label: '1 Frittata Slice (250g)', weightGrams: 250, multiplier: 2.5 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Frittata02.jpg/960px-Frittata02.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 15,
    ingredients: ['Liquid Egg Whites (200ml)', '1 Whole Egg', 'Lean Turkey Bacon (30g)', 'Baby Spinach & Bell Peppers', 'Feta (15g)'],
    cooking_steps: [
      'Sauté diced turkey bacon and baby spinach in an oven-safe skillet.',
      'Whisk egg whites with one whole egg for golden richness and pour over skillet.',
      'Bake or broil for 8 minutes until fluffed, golden, and firm.',
    ],
    health_benefits: ['40g+ pure bioavailable protein with minimal fat footprint', 'Ideal for contest cutting or high-protein bulking', 'High volume satiety'],
  },
  {
    id: 'food-hp-ln-01',
    name: 'Lean Ground Beef & Jasmine Rice Power Bowl',
    diet_type: 'high_protein',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 175,
    protein_g: 16,
    carbs_g: 18,
    fat_g: 4.5,
    fiber_g: 1.2,
    standard_serving_grams: 350,
    serving_options: [
      { label: 'Regular Bowl (350g)', weightGrams: 350, multiplier: 3.5 },
      { label: 'Mass Gainer Bowl (500g)', weightGrams: 500, multiplier: 5.0 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e3/Gyudon_by_katorisi_in_Tokyo.jpg/960px-Gyudon_by_katorisi_in_Tokyo.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 25,
    ingredients: ['95% Lean Ground Beef (180g)', 'Cooked Jasmine Rice (150g)', 'Bell Peppers', 'Onions', 'Low-Sodium Soy Sauce', 'Garlic'],
    cooking_steps: [
      'Brown lean minced beef in a skillet, draining any residual fats.',
      'Add minced garlic, diced bell peppers, and low sodium seasonings.',
      'Simmer for 8 minutes until vegetables are tender-crisp.',
      'Serve alongside warm steamed Jasmine rice for clean glycogen replenishment.',
    ],
    health_benefits: ['High bioavailable Heme-Iron and Zinc for testosterone support', 'Creatine naturally present in red meat for explosive strength', 'Fast-digesting clean carbs'],
  },
  {
    id: 'food-hp-ln-02',
    name: 'Grilled Sirloin Steak & Roasted Baby Potatoes',
    diet_type: 'high_protein',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 180,
    protein_g: 22,
    carbs_g: 12,
    fat_g: 5.2,
    fiber_g: 1.5,
    standard_serving_grams: 320,
    serving_options: [
      { label: 'Standard Plate (320g)', weightGrams: 320, multiplier: 3.2 },
    ],
    image_url: 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 20,
    ingredients: ['Lean Grass-Fed Sirloin (180g)', 'Baby Potatoes (120g)', 'Rosemary', 'Garlic Cloves', 'Olive Oil spray'],
    cooking_steps: [
      'Roast halved baby potatoes with rosemary and garlic at 200°C for 20 mins.',
      'Sear seasoned sirloin on cast iron skillet for 3.5 minutes per side for medium-rare perfection.',
      'Rest steak for 5 minutes before carving against the grain.',
    ],
    health_benefits: ['High B-Vitamins (B6, B12) for red blood cell synthesis', 'Potassium-dense potatoes support osmotic muscle pump', 'Superior amino acid profile'],
  },
  {
    id: 'food-hp-dn-01',
    name: 'Grilled Turkey Breast Steaks with Asparagus',
    diet_type: 'high_protein',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 135,
    protein_g: 30,
    carbs_g: 0,
    fat_g: 1.8,
    fiber_g: 0,
    standard_serving_grams: 200,
    serving_options: [
      { label: '1 Fillet (200g)', weightGrams: 200, multiplier: 2 },
      { label: 'Double Fillet (350g)', weightGrams: 350, multiplier: 3.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 18,
    ingredients: ['Lean Turkey Breast (200g)', 'Smoked Paprika', 'Thyme', 'Garlic', 'Olive Oil spray'],
    cooking_steps: [
      'Rub turkey breast with smoked paprika, dried thyme, and sea salt.',
      'Lightly coat skillet with olive oil spray.',
      'Grill on medium heat for 6 minutes per side until fully cooked and juicy.',
    ],
    health_benefits: ['Ultra-low fat bodybuilder staple for contest prep', 'High Tryptophan for serotonin production and sound sleep', 'Maximizes protein synthesis'],
  },
  {
    id: 'food-hp-dn-02',
    name: 'Lemon Pepper Tilapia Fillet & Steamed Quinoa',
    diet_type: 'high_protein',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 125,
    protein_g: 22,
    carbs_g: 6.5,
    fat_g: 1.8,
    fiber_g: 1.0,
    standard_serving_grams: 250,
    serving_options: [
      { label: '1 Plate (250g)', weightGrams: 250, multiplier: 2.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 15,
    ingredients: ['White Tilapia Fillet (200g)', 'Steamed Quinoa (60g)', 'Lemon Zest', 'Cracked Black Pepper', 'Fresh Parsley'],
    cooking_steps: [
      'Dust tilapia fillets with lemon zest, cracked pepper, and sea salt.',
      'Pan-sear in a non-stick skillet for 3 minutes per side until flaky white.',
      'Serve over a fluffy bed of steamed quinoa with lemon wedges.',
    ],
    health_benefits: ['Rapid gastric clearance without heaviness before bed', 'Pure white fish protein with zero saturated fat', 'Clean magnesium and zinc from quinoa'],
  },
  {
    id: 'food-hp-sn-01',
    name: 'Whipped High-Protein Cottage Cheese & Cinnamon',
    diet_type: 'high_protein',
    is_halal: true,
    category: 'snack',
    calories_per_100g: 105,
    protein_g: 14,
    carbs_g: 4.5,
    fat_g: 2.2,
    fiber_g: 0.5,
    standard_serving_grams: 200,
    serving_options: [
      { label: '1 Bowl (200g)', weightGrams: 200, multiplier: 2.0 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/16/Cottagecheese200px.jpg/960px-Cottagecheese200px.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 3,
    ingredients: ['Low-Fat Cottage Cheese (200g)', 'Ceylon Cinnamon (1/2 tsp)', 'Stevia / Drop of Vanilla', 'Crushed Walnuts (5g)'],
    cooking_steps: [
      'Blend or whip cottage cheese with vanilla and cinnamon until silky smooth.',
      'Top with a sprinkle of crushed walnuts for texture.',
    ],
    health_benefits: ['Slow-release micellar Casein prevents muscle breakdown', 'Cinnamon improves insulin receptor sensitivity', 'Satisfies sweet tooth with zero sugar'],
  },
  {
    id: 'food-hp-wo-01',
    name: 'Whey Protein Isolate Recovery Shake',
    diet_type: 'high_protein',
    is_halal: true,
    category: 'pre_post_workout',
    calories_per_100g: 90,
    protein_g: 18,
    carbs_g: 2.0,
    fat_g: 0.8,
    fiber_g: 0.5,
    standard_serving_grams: 300,
    serving_options: [
      { label: '1 Scoop in Water (300ml)', weightGrams: 300, multiplier: 3.0 },
      { label: '2 Scoops Anabolic Shake (500ml)', weightGrams: 500, multiplier: 5.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 2,
    ingredients: ['100% Whey Isolate Powder (30g)', 'Cold Filtered Water or Almond Milk (300ml)', 'Ice Cubes'],
    cooking_steps: [
      'Pour 300ml of cold water or unsweetened almond milk into shaker bottle.',
      'Add 1 rounded scoop (30g) of whey isolate powder.',
      'Shake vigorously for 15 seconds until smooth, frothy, and lump-free.',
      'Consume within 45 minutes post-training to maximize muscle protein synthesis.',
    ],
    health_benefits: ['Rapid gastric emptying and blood leucine spike within 20 minutes', 'Triggers mTOR signalling pathway for immediate myofibrillar repair', 'Zero lactose and zero digestive distress'],
  },
  {
    id: 'food-hp-wo-02',
    name: 'Anabolic Banana & Whey Protein Pancakes',
    diet_type: 'high_protein',
    is_halal: true,
    category: 'pre_post_workout',
    calories_per_100g: 165,
    protein_g: 18,
    carbs_g: 19,
    fat_g: 2.4,
    fiber_g: 2.5,
    standard_serving_grams: 220,
    serving_options: [
      { label: 'Stack of 3 Pancakes (220g)', weightGrams: 220, multiplier: 2.2 },
    ],
    image_url: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 10,
    ingredients: ['1 Scoop Whey Protein (Vanilla)', '1 Ripe Banana', 'Rolled Oats (40g blended)', '2 Egg Whites', 'Cinnamon & Baking Powder'],
    cooking_steps: [
      'Blend banana, egg whites, oat flour, and protein powder into a smooth batter.',
      'Pour onto a preheated non-stick pan on medium heat.',
      'Flip once bubbles appear on surface (approx 2 mins) and cook 1 min further.',
    ],
    health_benefits: ['High protein with clean energizing complex carbs', 'Potassium helps muscle hydration', 'Delicious post-workout anabolic reward'],
  },

  // =========================================================================
  // 3. VEGETARIAN / LACTO-OVO (Complete All 5 Subcategories)
  // =========================================================================
  {
    id: 'food-veg-bf-01',
    name: 'Greek Yogurt Berry & Sliced Almond Bowl',
    diet_type: 'veg',
    is_halal: true,
    category: 'breakfast',
    calories_per_100g: 115,
    protein_g: 10,
    carbs_g: 11,
    fat_g: 3.5,
    fiber_g: 2.2,
    standard_serving_grams: 250,
    serving_options: [
      { label: 'Small Bowl (150g)', weightGrams: 150, multiplier: 1.5 },
      { label: 'Standard Bowl (250g)', weightGrams: 250, multiplier: 2.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 5,
    ingredients: ['Authentic Non-Fat Greek Yogurt (200g)', 'Fresh Blueberries & Strawberries (50g)', 'Sliced Roasted Almonds (10g)', 'Chia Seeds (5g)'],
    cooking_steps: [
      'Scoop thick chilled Greek yogurt into a chilled bowl.',
      'Layer fresh antioxidant-rich mixed berries across the surface.',
      'Top with sliced roasted almonds and chia seeds for healthy crunch and omega-3s.',
    ],
    health_benefits: ['Live Probiotics bolster gut microbiome and nutrient absorption', 'Rich in Polyphenol antioxidants fighting workout oxidative stress', 'High satiety index keeps cravings suppressed'],
  },
  {
    id: 'food-veg-bf-02',
    name: 'Peanut Butter Banana Protein Oats',
    diet_type: 'veg',
    is_halal: true,
    category: 'breakfast',
    calories_per_100g: 140,
    protein_g: 7.5,
    carbs_g: 20,
    fat_g: 3.8,
    fiber_g: 3.0,
    standard_serving_grams: 300,
    serving_options: [
      { label: 'Standard Bowl (300g)', weightGrams: 300, multiplier: 3.0 },
      { label: 'Heavy Lifter Bowl (450g)', weightGrams: 450, multiplier: 4.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 10,
    ingredients: ['Rolled Oats (60g)', 'Skim Milk / Almond Milk (200ml)', 'Natural Peanut Butter (15g)', '1/2 Sliced Banana', 'Cinnamon Powder'],
    cooking_steps: [
      'Simmer rolled oats with milk on medium heat for 5-6 minutes until thick and creamy.',
      'Stir in cinnamon powder off heat.',
      'Top with fresh banana slices and a swirl of natural 100% roasted peanut butter.',
    ],
    health_benefits: ['Beta-glucan fiber slows gastric emptying for sustained steady energy', 'Potassium prevents intra-workout muscle cramping', 'Zero artificial sugars'],
  },
  {
    id: 'food-veg-ln-01',
    name: 'Yellow Moong Dal Tadka with Fragrant Cumin Rice',
    diet_type: 'veg',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 130,
    protein_g: 6.5,
    carbs_g: 21,
    fat_g: 2.5,
    fiber_g: 3.5,
    standard_serving_grams: 350,
    serving_options: [
      { label: '1 Bowl Dal + 1 Cup Rice (350g)', weightGrams: 350, multiplier: 3.5 },
      { label: 'Double Dal Bowl (500g)', weightGrams: 500, multiplier: 5.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 25,
    ingredients: ['Yellow Moong & Toor Dal (100g raw)', 'Basmati / Brown Rice (100g cooked)', 'Tomatoes & Onions', 'Turmeric & Cumin seeds', 'Ghee (1 tsp)'],
    cooking_steps: [
      'Pressure cook lentils with turmeric, salt, and water until creamy and soft.',
      'In a small pan, temper cumin seeds, garlic, and chopped tomatoes in 1 tsp ghee until aromatic.',
      'Pour hot tadka over dal and simmer for 3 minutes.',
      'Serve warm alongside fragrant cumin-infused basmati rice.',
    ],
    health_benefits: ['Combining lentils and grains yields complete complementary protein', 'Turmeric Curcumin provides potent anti-inflammatory joint recovery', 'Soluble fiber balances blood lipids'],
  },
  {
    id: 'food-veg-ln-02',
    name: 'Low-Fat Grilled Paneer & Capsicum Wrap',
    diet_type: 'veg',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 175,
    protein_g: 12,
    carbs_g: 17,
    fat_g: 6.8,
    fiber_g: 3.0,
    standard_serving_grams: 220,
    serving_options: [
      { label: '1 Wrap (220g)', weightGrams: 220, multiplier: 2.2 },
    ],
    image_url: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 15,
    ingredients: ['Whole Wheat Tortilla Wrap', 'Low-Fat Paneer Strips (100g)', 'Crunchy Bell Peppers & Onions', 'Mint Greek Yogurt Dressing'],
    cooking_steps: [
      'Pan-sear marinated paneer strips and sliced peppers with light spices for 5 mins.',
      'Warm the whole wheat tortilla on a flat tawa.',
      'Spread mint yogurt chutney, assemble filling, roll tight, and slice in half.',
    ],
    health_benefits: ['Convenient on-the-go high protein vegetarian lunch', 'Rich in capsanthin antioxidants', 'Sustained energy without afternoon crashes'],
  },
  {
    id: 'food-veg-dn-01',
    name: 'Char-Grilled Paneer Tikka Skewers',
    diet_type: 'veg',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 220,
    protein_g: 15,
    carbs_g: 6,
    fat_g: 16,
    fiber_g: 1.5,
    standard_serving_grams: 200,
    serving_options: [
      { label: '4 Skewers (200g)', weightGrams: 200, multiplier: 2 },
      { label: 'Platter (300g)', weightGrams: 300, multiplier: 3 },
    ],
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 25,
    ingredients: ['Low-Fat Cottage Cheese / Paneer (200g)', 'Greek Yogurt (3 tbsp)', 'Bell Peppers & Onions', 'Tikka Spices (Cumin, Coriander, Kashmiri Chili)', 'Mustard Oil (1 tsp)'],
    cooking_steps: [
      'Whisk Greek yogurt with spices, lemon juice, and a drop of mustard oil for authentic tandoori aroma.',
      'Cut paneer, capsicums, and onions into 1-inch cubes and coat thoroughly in marinade.',
      'Thread onto skewers and air fry or grill at 200°C for 12-14 minutes until charred edges appear.',
      'Sprinkle with chaat masala and fresh coriander.',
    ],
    health_benefits: ['Slow-digesting Casein protein prevents muscle catabolism overnight', 'Calcium and Phosphorus strengthen bone architecture', 'Zero refined carbohydrates'],
  },
  {
    id: 'food-veg-dn-02',
    name: 'Light Palak Paneer with Whole Wheat Roti',
    diet_type: 'veg',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 145,
    protein_g: 9.5,
    carbs_g: 8.0,
    fat_g: 8.5,
    fiber_g: 2.8,
    standard_serving_grams: 280,
    serving_options: [
      { label: '1 Bowl + 1 Roti (280g)', weightGrams: 280, multiplier: 2.8 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b7/Palakpaneer_Rayagada_Odisha_0009.jpg/960px-Palakpaneer_Rayagada_Odisha_0009.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 25,
    ingredients: ['Fresh Baby Spinach Puree (200g)', 'Low Fat Paneer Cubes (100g)', 'Garlic, Ginger & Green Chilies', 'Cumin & Coriander Spices', 'Olive Oil (1 tsp)'],
    cooking_steps: [
      'Blanch fresh spinach in boiling water for 2 mins, then blend with green chilies.',
      'Sauté garlic and ginger in olive oil, add spinach puree, spices, and cubed paneer.',
      'Simmer on gentle heat for 6 mins until flavors meld beautifully.',
    ],
    health_benefits: ['High non-heme iron and folate from spinach', 'Bioavailable calcium from milk protein', 'Comforting dinner with low glycemic index'],
  },
  {
    id: 'food-veg-sn-01',
    name: 'Spiced Namkeen Roasted Chickpeas & Almonds',
    diet_type: 'veg',
    is_halal: true,
    category: 'snack',
    calories_per_100g: 210,
    protein_g: 11,
    carbs_g: 24,
    fat_g: 8.0,
    fiber_g: 6.5,
    standard_serving_grams: 80,
    serving_options: [
      { label: '1 Snack Pack (80g)', weightGrams: 80, multiplier: 0.8 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Leblebi.jpg/960px-Leblebi.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 2,
    ingredients: ['Dry Roasted Black Chickpeas (50g)', 'Roasted Sliced Almonds (25g)', 'Chaat Masala', 'Himalayan Rock Salt'],
    cooking_steps: [
      'Toss dry roasted chickpeas and crisp almonds in a bowl.',
      'Dust with tangy chaat masala and pink salt.',
    ],
    health_benefits: ['Dense resistant starch feeds healthy colon bacteria', 'High plant fiber suppresses hunger between meals', 'Zero oil or frying'],
  },
  {
    id: 'food-veg-wo-01',
    name: 'Rice Cakes with Natural Peanut Butter & Honey',
    diet_type: 'veg',
    is_halal: true,
    category: 'pre_post_workout',
    calories_per_100g: 290,
    protein_g: 9,
    carbs_g: 48,
    fat_g: 7,
    fiber_g: 3,
    standard_serving_grams: 100,
    serving_options: [
      { label: '2 Rice Cakes (50g)', weightGrams: 50, multiplier: 0.5 },
      { label: '4 Rice Cakes (100g)', weightGrams: 100, multiplier: 1.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 3,
    ingredients: ['Crispy Brown/White Rice Cakes (4 cakes)', 'Natural Peanut Butter (20g)', 'Raw Honey (1 tsp)', 'Himalayan Pink Salt (pinch)'],
    cooking_steps: [
      'Spread natural peanut butter evenly across puffed rice cakes.',
      'Drizzle with a touch of raw organic honey.',
      'Sprinkle a tiny pinch of Himalayan pink salt for pre-workout muscle pump electrolytes.',
    ],
    health_benefits: ['Fast-acting clean glycogen fuel 30 minutes before heavy lifting', 'Sodium enhances intracellular pump and vascular volumization', 'Effortless digestion with zero bloating'],
  },

  // =========================================================================
  // 4. 100% VEGAN (Complete All 5 Subcategories)
  // =========================================================================
  {
    id: 'food-vg-bf-01',
    name: 'Turmeric Scrambled Tofu on Sourdough',
    diet_type: 'vegan',
    is_halal: true,
    category: 'breakfast',
    calories_per_100g: 135,
    protein_g: 11,
    carbs_g: 13,
    fat_g: 4.2,
    fiber_g: 2.8,
    standard_serving_grams: 220,
    serving_options: [
      { label: '1 Plate (220g)', weightGrams: 220, multiplier: 2.2 },
    ],
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 10,
    ingredients: ['Firm Organic Tofu (150g crumbled)', 'Nutritional Yeast (1 tbsp)', 'Ground Turmeric & Black Salt (Kala Namak)', 'Baby Spinach', 'Sourdough Toast (1 slice)'],
    cooking_steps: [
      'Crumble tofu into skillet with olive oil spray, turmeric, nutritional yeast, and black salt (for eggy sulfur aroma).',
      'Fold in baby spinach until wilted.',
      'Serve mounded over crisp toasted artisan sourdough.',
    ],
    health_benefits: ['100% plant-based cholesterol-free protein', 'Nutritional yeast provides essential Vitamin B-complex', 'Turmeric lowers joint stiffness'],
  },
  {
    id: 'food-vg-bf-02',
    name: 'Spirulina & Mixed Acai Berry Smoothie Bowl',
    diet_type: 'vegan',
    is_halal: true,
    category: 'breakfast',
    calories_per_100g: 95,
    protein_g: 4.5,
    carbs_g: 16,
    fat_g: 2.0,
    fiber_g: 3.5,
    standard_serving_grams: 300,
    serving_options: [
      { label: '1 Smoothie Bowl (300g)', weightGrams: 300, multiplier: 3.0 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/A%C3%A7a%C3%AD_do_Par%C3%A1.jpg/960px-A%C3%A7a%C3%AD_do_Par%C3%A1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 6,
    ingredients: ['Frozen Mixed Berries (100g)', 'Frozen Banana (1)', 'Organic Spirulina Powder (1 tsp)', 'Almond Milk (100ml)', 'Chia & Hemp Seeds (1 tbsp)'],
    cooking_steps: [
      'Blend frozen fruits with spirulina powder and splash of almond milk until thick soft-serve consistency.',
      'Spoon into bowl and garnish with hemp hearts, chia seeds, and fresh berries.',
    ],
    health_benefits: ['Massive antioxidant ORAC score combatting free radicals', 'Phycocyanin in spirulina supports cellular oxygen delivery', 'Zero dairy'],
  },
  {
    id: 'food-vg-ln-01',
    name: 'Quinoa & Chickpea Power Buddha Bowl',
    diet_type: 'vegan',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 145,
    protein_g: 6.8,
    carbs_g: 22,
    fat_g: 3.5,
    fiber_g: 4.5,
    standard_serving_grams: 350,
    serving_options: [
      { label: 'Standard Bowl (350g)', weightGrams: 350, multiplier: 3.5 },
      { label: 'Athlete Bowl (500g)', weightGrams: 500, multiplier: 5.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 20,
    ingredients: ['Cooked Quinoa (120g)', 'Boiled Chickpeas (100g)', 'Roasted Sweet Potato (60g)', 'Kale / Baby Spinach', 'Tahini Lemon Dressing (1 tbsp)'],
    cooking_steps: [
      'Cook fluffy quinoa in water with a pinch of sea salt.',
      'Roast spiced chickpeas and cubed sweet potatoes in oven at 200°C for 15 mins.',
      'Arrange vibrant beds of leafy greens, quinoa, roasted chickpeas, and avocado slices.',
      'Drizzle with velvety tahini, lemon juice, and roasted sesame seeds.',
    ],
    health_benefits: ['Quinoa is one of the few plant foods containing all 9 essential amino acids', 'High Dietary Fiber promotes clean digestion and gut biodiversity', 'Tahini provides bioavailable plant-derived Calcium'],
  },
  {
    id: 'food-vg-ln-02',
    name: 'Edamame & French Green Lentil Salad',
    diet_type: 'vegan',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 130,
    protein_g: 9.5,
    carbs_g: 15,
    fat_g: 3.8,
    fiber_g: 5.0,
    standard_serving_grams: 280,
    serving_options: [
      { label: '1 Large Bowl (280g)', weightGrams: 280, multiplier: 2.8 },
    ],
    image_url: 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 15,
    ingredients: ['Cooked Puy Green Lentils (120g)', 'Shelled Edamame (80g)', 'Diced Red Bell Pepper', 'Parsley & Mint', 'Lemon Olive Oil Dressing'],
    cooking_steps: [
      'Toss cooked firm lentils with steamed bright green edamame beans.',
      'Fold in finely diced red peppers, minced mint, and fresh parsley.',
      'Dress with cold-pressed olive oil, apple cider vinegar, and sea salt.',
    ],
    health_benefits: ['Dual plant protein synergy delivers complete BCAA profile', 'Exceptional prebiotic fiber content', 'Iron and folate for energy stamina'],
  },
  {
    id: 'food-vg-dn-01',
    name: 'Crispy Air-Fried Tofu & Broccoli Stir-Fry',
    diet_type: 'vegan',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 125,
    protein_g: 11,
    carbs_g: 6.5,
    fat_g: 6.0,
    fiber_g: 2.8,
    standard_serving_grams: 300,
    serving_options: [
      { label: '1 Serving (300g)', weightGrams: 300, multiplier: 3.0 },
      { label: 'Double Tofu Portion (450g)', weightGrams: 450, multiplier: 4.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 15,
    ingredients: ['Extra Firm Tofu (200g)', 'Fresh Broccoli Florets (100g)', 'Snap Peas & Carrots', 'Low-Sodium Tamari / Soy Sauce', 'Ginger Garlic Paste', 'Sesame Oil (1 tsp)'],
    cooking_steps: [
      'Press moisture from extra-firm tofu and cut into crisp 1-inch cubes.',
      'Air fry tofu cubes at 200°C for 12 minutes until deeply crunchy and golden.',
      'Stir-fry fresh broccoli florets and ginger-garlic paste in 1 tsp sesame oil on high wok heat.',
      'Toss crispy tofu with broccoli and tamari glaze.',
    ],
    health_benefits: ['Soy Isoflavones support arterial elasticity and recovery', 'Broccoli delivers Sulforaphane for cellular antioxidant defense', 'High Calcium and Iron for plant-based endurance athletes'],
  },
  {
    id: 'food-vg-dn-02',
    name: 'Coconut Red Lentil Curry with Brown Rice',
    diet_type: 'vegan',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 135,
    protein_g: 6.2,
    carbs_g: 19,
    fat_g: 4.0,
    fiber_g: 3.5,
    standard_serving_grams: 350,
    serving_options: [
      { label: 'Curry + Rice (350g)', weightGrams: 350, multiplier: 3.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 25,
    ingredients: ['Red Split Lentils (100g)', 'Light Coconut Milk (100ml)', 'Crushed Tomatoes', 'Curry Spices, Ginger & Garlic', 'Steamed Brown Rice (100g)'],
    cooking_steps: [
      'Simmer red lentils with aromatics, crushed tomatoes, and spices for 15 mins.',
      'Stir in light coconut milk for silky velvet texture; simmer for 5 mins.',
      'Serve over warm nutty brown rice with fresh lime juice.',
    ],
    health_benefits: ['Easily digestible plant comfort food', 'Medium-chain triglycerides in coconut aid energy without heavy fat storage', 'Potassium balance'],
  },
  {
    id: 'food-vg-sn-01',
    name: 'Overnight Chia Seed Coconut Pudding',
    diet_type: 'vegan',
    is_halal: true,
    category: 'snack',
    calories_per_100g: 135,
    protein_g: 4.5,
    carbs_g: 10,
    fat_g: 8.5,
    fiber_g: 6.5,
    standard_serving_grams: 200,
    serving_options: [
      { label: '1 Jar (200g)', weightGrams: 200, multiplier: 2.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 5,
    ingredients: ['Black Chia Seeds (30g)', 'Unsweetened Coconut Milk / Almond Milk (150ml)', 'Pure Vanilla Extract', 'Pomegranate Arils', 'Stevia or Pure Maple Syrup'],
    cooking_steps: [
      'Whisk chia seeds with coconut milk and vanilla extract in a mason jar.',
      'Let sit for 10 minutes, whisk once more to prevent clumping, then refrigerate for 4+ hours.',
      'Garnish with fresh ruby pomegranate seeds and toasted coconut flakes before serving.',
    ],
    health_benefits: ['Dense Alpha-Linolenic Acid (ALA) Plant Omega-3s', 'Gel-forming mucilage fiber aids steady blood sugar control', 'Supports deep hydration through water-retaining seed matrix'],
  },
  {
    id: 'food-vg-sn-02',
    name: '85% Dark Chocolate & Raw Walnut Medley',
    diet_type: 'vegan',
    is_halal: true,
    category: 'snack',
    calories_per_100g: 580,
    protein_g: 12,
    carbs_g: 22,
    fat_g: 48,
    fiber_g: 9.0,
    standard_serving_grams: 40,
    serving_options: [
      { label: 'Handful Snack (40g)', weightGrams: 40, multiplier: 0.4 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cd/Green_and_Black%27s_dark_chocolate_bar_2.jpg/960px-Green_and_Black%27s_dark_chocolate_bar_2.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 1,
    ingredients: ['85% Extra Dark Chocolate Chunks (20g)', 'Raw Organic Halved Walnuts (20g)'],
    cooking_steps: [
      'Pair bitter antioxidant dark chocolate pieces with crunchy brain-shaped walnuts.',
    ],
    health_benefits: ['Flavanols improve cerebral microvascular blood flow', 'Neuroprotective ALA fats protect brain cells', 'Powerful dopamine booster'],
  },
  {
    id: 'food-vg-wo-01',
    name: 'Pea Protein & Rolled Oat Energy Balls',
    diet_type: 'vegan',
    is_halal: true,
    category: 'pre_post_workout',
    calories_per_100g: 340,
    protein_g: 20,
    carbs_g: 38,
    fat_g: 12,
    fiber_g: 7.0,
    standard_serving_grams: 60,
    serving_options: [
      { label: '2 Energy Balls (60g)', weightGrams: 60, multiplier: 0.6 },
    ],
    image_url: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 10,
    ingredients: ['Organic Pea Protein (30g)', 'Rolled Oats (50g)', 'Medjool Dates (4 pitted)', 'Almond Butter (20g)', 'Chia Seeds'],
    cooking_steps: [
      'Pulse pitted dates, oats, pea protein, and almond butter in a food processor until dough forms.',
      'Roll into bite-sized balls and chill in fridge for 20 mins.',
    ],
    health_benefits: ['Clean plant fuel 45 mins before training', 'Zero artificial sweeteners or binders', 'High arginine content supports nitric oxide vasodilation'],
  },

  // =========================================================================
  // 5. KETO / LOW CARB (Complete All 5 Subcategories)
  // =========================================================================
  {
    id: 'food-kt-bf-01',
    name: 'Cheesy Spinach & Mushroom Omelette',
    diet_type: 'keto',
    is_halal: true,
    category: 'breakfast',
    calories_per_100g: 190,
    protein_g: 13,
    carbs_g: 1.8,
    fat_g: 15,
    fiber_g: 0.8,
    standard_serving_grams: 220,
    serving_options: [
      { label: '2-Egg Omelette (150g)', weightGrams: 150, multiplier: 1.5 },
      { label: '3-Egg Keto Supreme (220g)', weightGrams: 220, multiplier: 2.2 },
    ],
    image_url: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 10,
    ingredients: ['3 Large Whole Eggs', 'Baby Spinach (50g)', 'Sliced Button Mushrooms (40g)', 'Cheddar or Mozzarella Cheese (30g)', 'Butter (1 tsp)'],
    cooking_steps: [
      'Sauté sliced mushrooms and fresh spinach in butter until tender and moisture evaporates.',
      'Whisk eggs with a splash of cream, salt, and black pepper until frothy.',
      'Pour eggs into hot skillet; once set, add cheese and vegetables to one half and fold over.',
      'Slide onto plate and enjoy while cheese is molten and stretchy.',
    ],
    health_benefits: ['Zero glycemic spike sustains deep ketosis and fat adaptation', 'Choline in egg yolks bolsters neurotransmitter synthesis and liver health', 'Lutein & Zeaxanthin protect ocular wellness'],
  },
  {
    id: 'food-kt-bf-02',
    name: 'Baked Eggs in Hass Avocado Halves',
    diet_type: 'keto',
    is_halal: true,
    category: 'breakfast',
    calories_per_100g: 175,
    protein_g: 8.5,
    carbs_g: 2.2,
    fat_g: 15,
    fiber_g: 5.0,
    standard_serving_grams: 200,
    serving_options: [
      { label: '2 Avocado Halves (200g)', weightGrams: 200, multiplier: 2.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 15,
    ingredients: ['1 Whole Hass Avocado (halved, pit removed)', '2 Small Eggs', 'Smoked Sea Salt & Pepper', 'Chives'],
    cooking_steps: [
      'Scoop a spoonful out of each avocado half cavity to fit egg yolk.',
      'Crack an egg into each avocado half, season with salt and paprika.',
      'Bake at 200°C (400°F) for 12-14 minutes until whites set firm.',
    ],
    health_benefits: ['Monounsaturated fatty acid matrix sustains stable blood ketones', 'High potassium eliminates keto adaptation fatigue', 'Zero insulin spikes'],
  },
  {
    id: 'food-kt-ln-01',
    name: 'Avocado & Grilled Chicken Keto Salad',
    diet_type: 'keto',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 160,
    protein_g: 15,
    carbs_g: 2.5,
    fat_g: 10,
    fiber_g: 2.0,
    standard_serving_grams: 300,
    serving_options: [
      { label: 'Standard Keto Bowl (300g)', weightGrams: 300, multiplier: 3.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 15,
    ingredients: ['Grilled Chicken Thighs or Breast (150g)', '1 Whole Ripe Avocado', 'Romaine Lettuce & Arugula', 'Walnuts (15g)', 'Extra Virgin Olive Oil & Lemon Dressing'],
    cooking_steps: [
      'Chop crisp romaine and peppery arugula into a wide serving bowl.',
      'Dice seasoned grilled chicken and creamy ripe avocado.',
      'Top with toasted walnut pieces and toss in extra virgin olive oil vinaigrette.',
    ],
    health_benefits: ['High potassium and magnesium prevent keto flu electrolytes drop', 'Clean monounsaturated fats fuel ketone body production', 'Zero refined carbohydrates'],
  },
  {
    id: 'food-kt-ln-02',
    name: 'Keto Cauliflower Crust Mozzarella Pizza',
    diet_type: 'keto',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 185,
    protein_g: 13,
    carbs_g: 3.8,
    fat_g: 13,
    fiber_g: 2.5,
    standard_serving_grams: 250,
    serving_options: [
      { label: 'Personal Keto Pizza (250g)', weightGrams: 250, multiplier: 2.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 25,
    ingredients: ['Grated Cauliflower (200g squeezed dry)', 'Mozzarella & Parmesan (100g)', '1 Egg', 'Sugar-Free Tomato Basil Sauce', 'Fresh Basil Leaves'],
    cooking_steps: [
      'Mix squeezed dry cauliflower rice with egg and parmesan to form dough disc.',
      'Bake crust at 220°C for 15 mins until golden and crisp.',
      'Top with low-carb tomato sauce and mozzarella; broil for 4 minutes until bubbling.',
    ],
    health_benefits: ['Cures pizza cravings on strict under-20g carb keto diets', 'High calcium and satiating fats', 'Gluten-free and gut friendly'],
  },
  {
    id: 'food-kt-dn-01',
    name: 'Herb Butter Basted Ribeye Steak & Greens',
    diet_type: 'keto',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 260,
    protein_g: 22,
    carbs_g: 0.5,
    fat_g: 19,
    fiber_g: 0.5,
    standard_serving_grams: 250,
    serving_options: [
      { label: '1 Ribeye Steak (250g)', weightGrams: 250, multiplier: 2.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 18,
    ingredients: ['Grass-Fed Ribeye Steak (250g)', 'Grass-Fed Butter (15g)', 'Fresh Rosemary & Garlic', 'Steamed Green Beans / Broccoli (80g)'],
    cooking_steps: [
      'Season thick ribeye steak with coarse sea salt and cracked black pepper.',
      'Sear on screaming hot cast iron skillet for 3 mins per side, basting with rosemary-garlic butter.',
      'Rest for 6 minutes; serve with buttered green beans.',
    ],
    health_benefits: ['Ideal ketogenic fat-to-protein ratio', 'Conjugated Linoleic Acid (CLA) from grass-fed beef supports body recomposition', 'Deep metabolic satiety'],
  },
  {
    id: 'food-kt-dn-02',
    name: 'Wild Salmon in Lemon Butter Dill Sauce',
    diet_type: 'keto',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 215,
    protein_g: 21,
    carbs_g: 1.0,
    fat_g: 14,
    fiber_g: 0.5,
    standard_serving_grams: 220,
    serving_options: [
      { label: '1 Salmon Fillet (220g)', weightGrams: 220, multiplier: 2.2 },
    ],
    image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 15,
    ingredients: ['Fresh Salmon (200g)', 'Butter (10g)', 'Heavy Cream (1 tbsp)', 'Fresh Lemon & Dill', 'Zucchini ribbons (60g)'],
    cooking_steps: [
      'Pan-sear salmon fillet until skin is crispy and flesh is flaky pink.',
      'Make quick pan sauce with melted butter, lemon juice, heavy cream, and dill.',
      'Serve atop sautéed buttery zucchini ribbons.',
    ],
    health_benefits: ['Dense Omega-3 to Omega-6 ratio', 'Promotes anti-inflammatory ketone metabolism', 'High Vitamin B12'],
  },
  {
    id: 'food-kt-sn-01',
    name: 'Salted Roasted Macadamia & Pecan Nut Mix',
    diet_type: 'keto',
    is_halal: true,
    category: 'snack',
    calories_per_100g: 690,
    protein_g: 8.5,
    carbs_g: 5.0,
    fat_g: 74,
    fiber_g: 8.5,
    standard_serving_grams: 35,
    serving_options: [
      { label: '1 Keto Portion (35g)', weightGrams: 35, multiplier: 0.35 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Almonds_-_in_shell%2C_shell_cracked_open%2C_shelled%2C_blanched.jpg/960px-Almonds_-_in_shell%2C_shell_cracked_open%2C_shelled%2C_blanched.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 1,
    ingredients: ['Raw Macadamia Nuts (20g)', 'Roasted Pecans (15g)', 'Coarse Sea Salt'],
    cooking_steps: [
      'Toss nuts with sea salt for the ultimate portable keto fat-bomb snack.',
    ],
    health_benefits: ['Highest healthy monounsaturated fat concentration among nuts', 'Sub-2g net carbs per serving', 'Instant craving relief'],
  },
  {
    id: 'food-kt-wo-01',
    name: 'Keto Bulletproof Coffee with MCT & Ghee',
    diet_type: 'keto',
    is_halal: true,
    category: 'pre_post_workout',
    calories_per_100g: 75,
    protein_g: 0.2,
    carbs_g: 0.3,
    fat_g: 8.5,
    fiber_g: 0,
    standard_serving_grams: 250,
    serving_options: [
      { label: '1 Mug (250ml)', weightGrams: 250, multiplier: 2.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 4,
    ingredients: ['Freshly Brewed Espresso / Dark Roast (200ml)', 'Pure C8 MCT Oil (1 tbsp)', 'Grass-Fed Ghee (1 tsp)', 'Cinnamon (dash)'],
    cooking_steps: [
      'Brew a strong piping hot cup of black coffee.',
      'Add MCT oil and ghee into blender with coffee; blend on high for 20 seconds until creamy latte foam develops.',
    ],
    health_benefits: ['C8 MCTs convert directly into liver ketones in under 15 minutes', 'Sustained cognitive focus and pre-workout endurance with zero carb crash', 'Fast lipid mobilization'],
  },

  // =========================================================================
  // 6. DESI / SOUTH ASIAN (Complete All 5 Subcategories)
  // =========================================================================
  {
    id: 'food-ds-bf-01',
    name: 'Desi Spiced Egg Anda Bhurji with Chapati',
    diet_type: 'desi',
    is_halal: true,
    category: 'breakfast',
    calories_per_100g: 165,
    protein_g: 11,
    carbs_g: 12,
    fat_g: 8.0,
    fiber_g: 2.0,
    standard_serving_grams: 220,
    serving_options: [
      { label: 'Bhurji + 1 Multigrain Roti (220g)', weightGrams: 220, multiplier: 2.2 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/06/Spicy_egg_bhurji_%40_the_eggfactory.jpg/960px-Spicy_egg_bhurji_%40_the_eggfactory.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 10,
    ingredients: ['2 Whole Eggs + 1 Egg White', 'Finely Diced Onions & Tomatoes', 'Green Chilies & Fresh Coriander', 'Turmeric, Cumin & Garam Masala', 'Olive Oil (1/2 tsp)'],
    cooking_steps: [
      'Sauté onions, green chilies, and ginger in 1/2 tsp olive oil until translucent.',
      'Add chopped tomatoes and ground spices; cook until soft.',
      'Whisk eggs and pour in; scramble gently until soft and fluffy.',
      'Garnish with fresh coriander leaves and serve with warm multigrain roti.',
    ],
    health_benefits: ['High-protein traditional South Asian breakfast', 'Thermogenic spices boost resting metabolic rate', 'Satisfies for 4+ hours'],
  },
  {
    id: 'food-ds-bf-02',
    name: 'High-Protein Besan & Flaxseed Cheela',
    diet_type: 'desi',
    is_halal: true,
    category: 'breakfast',
    calories_per_100g: 150,
    protein_g: 9.5,
    carbs_g: 18,
    fat_g: 4.5,
    fiber_g: 4.5,
    standard_serving_grams: 180,
    serving_options: [
      { label: '2 Cheelas (180g)', weightGrams: 180, multiplier: 1.8 },
    ],
    image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 12,
    ingredients: ['Gram Flour / Besan (60g)', 'Ground Flaxseed (10g)', 'Grated Carrots & Capsicum', 'Ajwain (Carom seeds) & Turmeric', 'Water to make thin batter'],
    cooking_steps: [
      'Whisk besan, flaxseed, carom seeds, turmeric, salt, and water into smooth savory batter.',
      'Pour ladleful onto hot non-stick tawa; spread in circular motions.',
      'Cook for 2.5 mins per side until crisp and golden brown.',
      'Serve with homemade mint-coriander green chutney.',
    ],
    health_benefits: ['Gluten-free plant protein with high fiber', 'Ajwain aids gastric digestion and prevents bloating', 'Omega-3 fats from ground flaxseeds'],
  },
  {
    id: 'food-ds-ln-01',
    name: 'Homestyle Daal Chawal & Kachumber Salad',
    diet_type: 'desi',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 135,
    protein_g: 6.0,
    carbs_g: 22,
    fat_g: 2.2,
    fiber_g: 3.5,
    standard_serving_grams: 350,
    serving_options: [
      { label: '1 Thali Bowl (350g)', weightGrams: 350, multiplier: 3.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 25,
    ingredients: ['Mixed Moong-Masoor Lentils (100g cooked)', 'Steamed Basmati Rice (100g cooked)', 'Cucumber, Tomato & Onion Salad', 'Lemon Juice & Cumin Tadka'],
    cooking_steps: [
      'Cook lentils with turmeric, pink salt, and ginger until creamy.',
      'Temper with cumin seeds and minced garlic in 1 tsp olive oil or desi ghee.',
      'Serve warm alongside fluffy basmati rice and crisp lemon kachumber salad.',
    ],
    health_benefits: ['Timeless subcontinent comfort staple with balanced amino acids', 'Fiber helps lower blood cholesterol', 'Easy on the digestive system'],
  },
  {
    id: 'food-ds-ln-02',
    name: 'Lean Mutton Qeema with Peas & Bran Roti',
    diet_type: 'desi',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 170,
    protein_g: 18,
    carbs_g: 11,
    fat_g: 5.5,
    fiber_g: 2.5,
    standard_serving_grams: 280,
    serving_options: [
      { label: '1 Plate Qeema + 1 Roti (280g)', weightGrams: 280, multiplier: 2.8 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/Keema_Matar_%28a_dish_from_India%29.jpg/960px-Keema_Matar_%28a_dish_from_India%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 30,
    ingredients: ['Lean Minced Goat Meat / Mutton (180g)', 'Green Sweet Peas (40g)', 'Ginger Julienned & Crushed Garlic', 'Whole Spices & Low-Oil Bhunai', 'Whole Wheat Bran Roti'],
    cooking_steps: [
      'Sauté minced mutton with crushed ginger-garlic and whole cardamom/cinnamon.',
      'Add pureed tomatoes, green peas, and simmer until meat is tender and water dries up.',
      'Garnish with mint and fresh ginger slivers; enjoy with whole wheat bran roti.',
    ],
    health_benefits: ['High bioavailable heme-iron prevents anemia in active lifters', 'Zinc for natural testosterone synthesis', 'Cooked clean with minimal saturated fat'],
  },
  {
    id: 'food-ds-dn-01',
    name: 'Olive Oil Chicken Karahi (Desi Clean Cut)',
    diet_type: 'desi',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 155,
    protein_g: 22,
    carbs_g: 3.5,
    fat_g: 5.8,
    fiber_g: 1.2,
    standard_serving_grams: 280,
    serving_options: [
      { label: '1 Serving Karahi (280g)', weightGrams: 280, multiplier: 2.8 },
      { label: 'Karahi + 1 Multigrain Roti', weightGrams: 340, multiplier: 3.4 },
    ],
    image_url: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 25,
    ingredients: ['Skinless Chicken pieces (250g)', 'Fresh Ripe Tomatoes (3 medium)', 'Ginger Julienned & Crushed Garlic', 'Green Chilies', 'Olive Oil (1 tbsp only)', 'Coriander, Cumin, Black Pepper'],
    cooking_steps: [
      'Heat 1 tbsp olive oil in a traditional wok/karahi and sear chicken with ginger-garlic paste until white.',
      'Cover with halved fresh tomatoes; steam until tomato skins peel off easily.',
      'Cook on high flame (bhunai) until tomatoes dissolve into a rich, fragrant gravy without excessive oil.',
      'Garnish generously with ginger slivers, fresh green chilies, and crushed black pepper.',
    ],
    health_benefits: ['High protein traditional favorite optimized with heart-healthy olive oil', 'Tomatoes provide Lycopene antioxidant for prostate and cardiovascular health', 'Ginger and spices improve digestive enzymes'],
  },
  {
    id: 'food-ds-dn-02',
    name: 'Tandoori Char-Grilled Chicken Tikka Boti',
    diet_type: 'desi',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 150,
    protein_g: 28,
    carbs_g: 1.5,
    fat_g: 3.2,
    fiber_g: 0.5,
    standard_serving_grams: 220,
    serving_options: [
      { label: '1 Plate Tikka Boti (220g)', weightGrams: 220, multiplier: 2.2 },
      { label: 'Jumbo Meat Platter (350g)', weightGrams: 350, multiplier: 3.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 20,
    ingredients: ['Boneless Chicken Breast or Thigh (220g)', 'Low-fat Yogurt (2 tbsp)', 'Lemon Juice', 'Tikka Masala Spices', 'Garlic Ginger'],
    cooking_steps: [
      'Cut chicken into bite-sized cubes and marinate in yogurt, lemon juice, and red tikka spices for 2 hours.',
      'Skewer and char-grill over coal or in an oven broiler for 12 minutes, turning frequently.',
      'Serve with sliced red onions and fresh lemon wedges.',
    ],
    health_benefits: ['Pure protein with minimal carbohydrate footprint', 'Charred aromatics without heavy creamy sauces', 'Great for low-calorie cutting phases'],
  },
  {
    id: 'food-ds-dn-03',
    name: 'Charcoal Tandoori Fish Tikka with Mint Chutney',
    diet_type: 'desi',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 135,
    protein_g: 24,
    carbs_g: 1.8,
    fat_g: 3.0,
    fiber_g: 0.5,
    standard_serving_grams: 220,
    serving_options: [
      { label: '1 Plate Fish Tikka (220g)', weightGrams: 220, multiplier: 2.2 },
    ],
    image_url: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 18,
    ingredients: ['Boneless White Fish Fillet / Rahu / Snapper (220g)', 'Carom Seeds (Ajwain)', 'Kashmiri Red Chili & Garam Masala', 'Yogurt & Lemon Juice'],
    cooking_steps: [
      'Marinate fish cubes in lemon juice, carom seeds, ginger paste, and tandoori spices for 30 mins.',
      'Grill or air fry at 200°C for 10-12 minutes until flaky and charred at corners.',
      'Serve hot with raw onion rings and low-fat mint raita.',
    ],
    health_benefits: ['Ultra-clean lean protein', 'Carom seeds prevent any heavy fish aftertaste and aid gastric fire', 'High in selenium and iodine'],
  },
  {
    id: 'food-ds-sn-01',
    name: 'High-Protein Shami Kebabs (Air-Fried)',
    diet_type: 'desi',
    is_halal: true,
    category: 'snack',
    calories_per_100g: 165,
    protein_g: 21,
    carbs_g: 8.5,
    fat_g: 4.8,
    fiber_g: 2.5,
    standard_serving_grams: 140,
    serving_options: [
      { label: '2 Kebabs (140g)', weightGrams: 140, multiplier: 1.4 },
      { label: '4 Kebabs Post-Workout (280g)', weightGrams: 280, multiplier: 2.8 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/4th_October_2012_Shami_Kebab.jpg/960px-4th_October_2012_Shami_Kebab.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 30,
    ingredients: ['Lean Minced Beef or Chicken (200g)', 'Chana Dal / Split Chickpeas (40g)', 'Whole Garam Masala', 'Fresh Mint & Green Chilies', 'Egg white (for binding)'],
    cooking_steps: [
      'Boil lean meat and chana dal together with whole spices, ginger, and garlic until tender and dry.',
      'Pound or grind smoothly with fresh mint leaves and green chilies; shape into flat round patties.',
      'Brush lightly with egg white and air fry at 190°C for 10 minutes until crisp golden brown outside.',
      'Serve with homemade mint-coriander Greek yogurt dip.',
    ],
    health_benefits: ['Exceptional combination of animal and pulse proteins', 'Zero deep-frying removes 80% excess trans-fat calories', 'Perfect portable high-protein meal prep snack'],
  },
  {
    id: 'food-ds-sn-02',
    name: 'Roasted Fox Nuts (Phool Makhana) & Chana',
    diet_type: 'desi',
    is_halal: true,
    category: 'snack',
    calories_per_100g: 220,
    protein_g: 9.5,
    carbs_g: 36,
    fat_g: 3.5,
    fiber_g: 6.0,
    standard_serving_grams: 50,
    serving_options: [
      { label: '1 Large Bowl (50g)', weightGrams: 50, multiplier: 0.5 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Phool_Makhana.JPG/960px-Phool_Makhana.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 5,
    ingredients: ['Lotus Seeds / Phool Makhana (30g)', 'Roasted Black Chickpeas (20g)', 'Turmeric, Chaat Masala & Pink Salt', 'Desi Ghee (1/2 tsp)'],
    cooking_steps: [
      'Roast makhana on low flame in 1/2 tsp ghee until extremely crunchy.',
      'Dust with turmeric, black salt, and chaat masala; toss with roasted chana.',
    ],
    health_benefits: ['Low glycemic index superfood snack', 'Rich in kaempferol anti-aging flavonoids', 'High magnesium supports cardiovascular regulation'],
  },
  {
    id: 'food-ds-wo-01',
    name: 'Desi Roasted Sattu Chana Protein Drink',
    diet_type: 'desi',
    is_halal: true,
    category: 'pre_post_workout',
    calories_per_100g: 80,
    protein_g: 6.5,
    carbs_g: 12,
    fat_g: 1.2,
    fiber_g: 2.8,
    standard_serving_grams: 300,
    serving_options: [
      { label: '1 Big Glass (300ml)', weightGrams: 300, multiplier: 3.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 3,
    ingredients: ['Roasted Bengal Gram Flour / Sattu (40g)', 'Chilled Water (280ml)', 'Fresh Lemon Juice (1 tbsp)', 'Roasted Cumin Powder & Kala Namak', 'Finely Chopped Mint'],
    cooking_steps: [
      'Whisk sattu powder with chilled water until completely dissolved and free of lumps.',
      'Add lemon juice, roasted cumin powder, black rock salt, and chopped mint leaves.',
      'Serve cold 30 minutes before workout or as an instant natural post-workout fuel.',
    ],
    health_benefits: ['Subcontinent indigenous natural protein shake', 'Naturally cools internal core body temperature', 'Electrolytes prevent dehydration and cramping'],
  },

  // =========================================================================
  // 7. MEDITERRANEAN (Complete All 5 Subcategories)
  // =========================================================================
  {
    id: 'food-md-bf-01',
    name: 'Mediterranean Poached Eggs Shakshuka',
    diet_type: 'mediterranean',
    is_halal: true,
    category: 'breakfast',
    calories_per_100g: 140,
    protein_g: 9.5,
    carbs_g: 6.5,
    fat_g: 8.5,
    fiber_g: 2.0,
    standard_serving_grams: 250,
    serving_options: [
      { label: '1 Skillet Serving (250g)', weightGrams: 250, multiplier: 2.5 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Shakshuka_by_Calliopejen1.jpg/960px-Shakshuka_by_Calliopejen1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 15,
    ingredients: ['2 Large Whole Eggs', 'Crushed San Marzano Tomatoes (150g)', 'Red Bell Peppers & Onions', 'Garlic, Cumin & Smoked Paprika', 'Crumbled Feta (15g)', 'Extra Virgin Olive Oil (1 tsp)'],
    cooking_steps: [
      'Simmer diced onions, bell peppers, garlic, and tomatoes with cumin and paprika in olive oil until a thick sauce forms.',
      'Make two wells in the sauce and crack in whole eggs.',
      'Cover and simmer on low heat for 6 minutes until egg whites are set and yolks remain runny.',
      'Top with crumbled feta cheese and fresh parsley.',
    ],
    health_benefits: ['Lycopene absorption is amplified 3x when cooked with olive oil', 'High in bioavailable egg albumin and healthy fats', 'Keeps blood sugar stable all morning'],
  },
  {
    id: 'food-md-bf-02',
    name: 'Greek Labneh, Cucumber & Tomato Toast with Zaatar',
    diet_type: 'mediterranean',
    is_halal: true,
    category: 'breakfast',
    calories_per_100g: 155,
    protein_g: 8.5,
    carbs_g: 16,
    fat_g: 6.5,
    fiber_g: 2.8,
    standard_serving_grams: 180,
    serving_options: [
      { label: '2 Toasts (180g)', weightGrams: 180, multiplier: 1.8 },
    ],
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Labneh01.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled',
    prep_time_min: 6,
    ingredients: ['Artisan Sourdough / Pita (2 slices)', 'Strained Greek Labneh / Yogurt (60g)', 'Sliced Persian Cucumbers & Cherry Tomatoes', 'Wild Zaatar Herb Blend', 'Extra Virgin Olive Oil (1 tsp)'],
    cooking_steps: [
      'Toast sourdough slices until firm and golden.',
      'Spread thick tangy Greek labneh evenly over toast.',
      'Layer with thinly sliced crisp cucumbers and tomatoes, dust with fragrant zaatar, and finish with a drizzle of cold-pressed EVOO.',
    ],
    health_benefits: ['Fermented labneh delivers active gut-friendly probiotics', 'Zaatar herbs provide thymol and carvacrol antimicrobial antioxidants', 'Clean morning energy'],
  },
  {
    id: 'food-md-ln-01',
    name: 'Greek Village Salad with EVOO & Feta',
    diet_type: 'mediterranean',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 120,
    protein_g: 4.5,
    carbs_g: 4.0,
    fat_g: 9.5,
    fiber_g: 1.8,
    standard_serving_grams: 250,
    serving_options: [
      { label: '1 Large Bowl (250g)', weightGrams: 250, multiplier: 2.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    prep_time_min: 8,
    ingredients: ['Ripe Vine Tomatoes (150g)', 'Crisp Cucumbers (80g)', 'Authentic Greek Feta Cheese (40g)', 'Kalamata Olives (20g)', 'Extra Virgin Olive Oil (1 tbsp)', 'Dried Wild Oregano'],
    cooking_steps: [
      'Chop tomatoes and cucumbers into rustic bite-sized chunks.',
      'Add pitted Kalamata olives and thinly sliced red onions.',
      'Top with a single slab of sheep milk feta cheese and dust with wild Greek oregano.',
      'Generously drizzle cold-pressed extra virgin olive oil before serving.',
    ],
    health_benefits: ['High Polyphenol Extra Virgin Olive Oil boosts endothelial vascular function', 'Authentic feta delivers bioavailable calcium and probiotic cultures', 'Hydrating minerals support osmotic balance'],
  },
  {
    id: 'food-md-ln-02',
    name: 'Greek Lemon Herb Chicken Souvlaki with Tzatziki',
    diet_type: 'mediterranean',
    is_halal: true,
    category: 'lunch',
    calories_per_100g: 160,
    protein_g: 24,
    carbs_g: 3.5,
    fat_g: 5.5,
    fiber_g: 0.8,
    standard_serving_grams: 240,
    serving_options: [
      { label: '3 Skewers + Tzatziki (240g)', weightGrams: 240, multiplier: 2.4 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cd/%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CF%8C_%CE%A3%CE%BF%CF%85%CE%B2%CE%BB%CE%AC%CE%BA%CE%B9_-_panoramio.jpg/960px-%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CF%8C_%CE%A3%CE%BF%CF%85%CE%B2%CE%BB%CE%AC%CE%BA%CE%B9_-_panoramio.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 20,
    ingredients: ['Chicken Breast Cubes (200g)', 'Greek Olive Oil, Lemon, Oregano & Garlic Marinade', 'Homemade Cucumber Tzatziki (40g)'],
    cooking_steps: [
      'Marinate diced chicken in lemon juice, olive oil, garlic, and wild Greek oregano for 1 hour.',
      'Thread onto skewers and char-grill for 10 minutes over high heat.',
      'Serve alongside cooling cucumber-garlic Greek yogurt tzatziki.',
    ],
    health_benefits: ['Lean Mediterranean protein power meal', 'Garlic and olive oil promote arterial dilation', 'Zero processed sauces'],
  },
  {
    id: 'food-md-dn-01',
    name: 'Grilled Whole Seabass with Lemon & Herbs',
    diet_type: 'mediterranean',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 125,
    protein_g: 23,
    carbs_g: 0,
    fat_g: 3.5,
    fiber_g: 0,
    standard_serving_grams: 250,
    serving_options: [
      { label: '1 Whole Fish (250g meat)', weightGrams: 250, multiplier: 2.5 },
    ],
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 20,
    ingredients: ['Fresh Mediterranean Seabass (1 whole)', 'Fresh Rosemary & Thyme', 'Lemon Slices', 'Garlic Cloves', 'Olive Oil spray'],
    cooking_steps: [
      'Score the seabass skin on both sides and stuff cavity with lemon slices, garlic, and fresh herbs.',
      'Season with sea salt and black pepper.',
      'Grill over medium-high heat for 7 minutes per side until skin is blistered and flesh flakes effortlessly.',
    ],
    health_benefits: ['Ultra-clean marine protein profile', 'Abundant in Iodine, Selenium, and Vitamin D3', 'Supports thyroid hormone synthesis and optimal metabolic rate'],
  },
  {
    id: 'food-md-dn-02',
    name: 'Rosemary Baked Chicken Thighs & Roasted Veggies',
    diet_type: 'mediterranean',
    is_halal: true,
    category: 'dinner',
    calories_per_100g: 165,
    protein_g: 20,
    carbs_g: 5.5,
    fat_g: 7.2,
    fiber_g: 1.8,
    standard_serving_grams: 280,
    serving_options: [
      { label: '1 Plate (280g)', weightGrams: 280, multiplier: 2.8 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d9/Max%27s_Roasted_Chicken_-_Evan_Swigart.jpg/960px-Max%27s_Roasted_Chicken_-_Evan_Swigart.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 30,
    ingredients: ['Skinless Bone-In Chicken Thighs (200g)', 'Zucchini, Bell Peppers & Red Onions (100g)', 'Kalamata Olives', 'Fresh Rosemary Sprigs & Olive Oil'],
    cooking_steps: [
      'Toss chicken thighs and rustic cut vegetables with olive oil, crushed garlic, and fresh rosemary.',
      'Roast in oven at 200°C (400°F) for 30 minutes until chicken is tender and vegetables are caramelized.',
    ],
    health_benefits: ['Rich in monounsaturated fats and essential micronutrients', 'Rosemary rosmarinic acid fights cellular oxidative aging', 'Deeply satisfying dinner'],
  },
  {
    id: 'food-md-sn-01',
    name: 'Creamy Tahini Hummus with Crisp Veggie Sticks',
    diet_type: 'mediterranean',
    is_halal: true,
    category: 'snack',
    calories_per_100g: 165,
    protein_g: 7.8,
    carbs_g: 14,
    fat_g: 9.5,
    fiber_g: 5.5,
    standard_serving_grams: 150,
    serving_options: [
      { label: '1 Bowl Hummus + Veggies (150g)', weightGrams: 150, multiplier: 1.5 },
    ],
    image_url: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/Lebanese_style_hummus.jpg/960px-Lebanese_style_hummus.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
    prep_time_min: 5,
    ingredients: ['Cooked Chickpeas (100g)', 'Pure Sesame Tahini (20g)', 'Lemon Juice & Minced Garlic', 'EVOO (1 tsp)', 'Carrot & Cucumber Sticks'],
    cooking_steps: [
      'Blend chickpeas with tahini, lemon juice, ice water, and garlic until silky smooth.',
      'Spoon into bowl, make an oil well, drizzle extra virgin olive oil, and dust with paprika.',
      'Dip crunchy fresh carrot and celery sticks.',
    ],
    health_benefits: ['Soluble fiber stabilizes LDL cholesterol', 'Plant sterols from sesame tahini support hormone production', 'Clean, whole-food snacking'],
  },
  {
    id: 'food-md-wo-01',
    name: 'Greek Honey, Walnut & Dried Fig Power Fuel',
    diet_type: 'mediterranean',
    is_halal: true,
    category: 'pre_post_workout',
    calories_per_100g: 270,
    protein_g: 7.0,
    carbs_g: 44,
    fat_g: 8.5,
    fiber_g: 5.0,
    standard_serving_grams: 100,
    serving_options: [
      { label: '1 Pre-Workout Cup (100g)', weightGrams: 100, multiplier: 1.0 },
    ],
    image_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&auto=format&fit=crop&q=80',
    prep_time_min: 3,
    ingredients: ['Dried Black Mission Figs (3 figs)', 'Raw Halved Walnuts (20g)', 'Pure Raw Thyme Honey (1 tsp)', 'Greek Yogurt (3 tbsp)'],
    cooking_steps: [
      'Layer thick Greek yogurt in a glass with chopped dried figs and walnut halves.',
      'Drizzle with raw unfiltered honey for explosive pre-workout ATP energy.',
    ],
    health_benefits: ['Dense natural glucose and fructose for quick pre-workout glycogen', 'Magnesium and calcium from figs enhance muscle contractions', 'Omega-3 fats support blood flow'],
  },
];
